// components/BaziChart.tsx
import React, { useState, useRef, useEffect } from 'react';
import { BaziChart as BaziChartType, PillarData } from '../types';

interface Props {
  chart: BaziChartType;
}

// Relationship Logic
const ZHI_RELATIONS: Record<string, { clash: string[], combine: string[] }> = {
  '子': { clash: ['午'], combine: ['丑'] },
  '丑': { clash: ['未'], combine: ['子'] },
  '寅': { clash: ['申'], combine: ['亥'] },
  '卯': { clash: ['酉'], combine: ['戌'] },
  '辰': { clash: ['戌'], combine: ['酉'] },
  '巳': { clash: ['亥'], combine: ['申'] },
  '午': { clash: ['子'], combine: ['未'] },
  '未': { clash: ['丑'], combine: ['午'] },
  '申': { clash: ['寅'], combine: ['巳'] },
  '酉': { clash: ['卯'], combine: ['辰'] },
  '戌': { clash: ['辰'], combine: ['卯'] },
  '亥': { clash: ['巳'], combine: ['寅'] },
};

const getRelationship = (z1: string, z2: string): { type: 'clash' | 'combine' | null, label: string } => {
  if (!z1 || !z2) return { type: null, label: '' };
  const rel = ZHI_RELATIONS[z1];
  if (rel?.clash.includes(z2)) return { type: 'clash', label: '冲' };
  if (rel?.combine.includes(z2)) return { type: 'combine', label: '合' };
  return { type: null, label: '' };
};

interface PillarCardProps {
  title: string;
  data: PillarData;
  highlight?: boolean;
  setZhiRef: (el: HTMLDivElement | null) => void;
  onHover: (isHovering: boolean) => void;
}

const PillarCard: React.FC<PillarCardProps> = ({ title, data, highlight, setZhiRef, onHover }) => {
  return (
    <div className={`
        relative flex flex-col items-center
        bg-white rounded-xl shadow-[0_2px_8px_rgba(0,0,0,0.04)] 
        transition-all duration-300 hover:shadow-[0_4px_12px_rgba(0,0,0,0.08)]
        border border-slate-100 overflow-hidden group
        ${highlight ? 'ring-2 ring-violet-500/50 shadow-violet-100' : ''} 
        z-10 min-w-[70px] sm:min-w-[90px]
    `}>
      {/* Title Header */}
      <div className={`
          w-full text-center py-1.5 text-[10px] sm:text-xs font-bold tracking-widest uppercase
          ${highlight ? 'bg-violet-50 text-violet-700' : 'bg-slate-50 text-slate-500'}
      `}>
        {title}
      </div>

      {/* Main Content Area */}
      <div className="w-full px-2 py-3 flex flex-col items-center gap-2">

        {/* Ten Gods (Heaven) */}
        <div className="text-[10px] text-slate-400 font-medium h-4 leading-none">
          {data.ganGod}
        </div>

        {/* Heavenly Stem */}
        <div className="text-3xl sm:text-4xl font-serif font-black text-slate-800 leading-none filter drop-shadow-sm">
          {data.gan}
        </div>

        {/* Earthly Branch */}
        <div
          ref={setZhiRef}
          onMouseEnter={() => onHover(true)}
          onMouseLeave={() => onHover(false)}
          className={`
                w-full text-center py-2 text-3xl sm:text-4xl font-serif font-black 
                cursor-help transition-colors rounded-lg
                ${highlight ? 'text-violet-900 bg-violet-50/50' : 'text-slate-800 hover:bg-slate-50'}
            `}
        >
          {data.zhi}
        </div>

        {/* Hidden Stems (CangGan) */}
        <div className="w-full flex flex-col gap-1 mt-1 pt-2 border-t border-slate-100/60 min-h-[50px]">
          {data.hiddenGan.map((gan, idx) => (
            <div key={idx} className="flex justify-between items-center text-[10px] px-1 group/item">
              <span className="text-slate-400 group-hover/item:text-slate-600 transition-colors w-1/2 text-left">{data.zhiGod[idx] || '-'}</span>
              <span className="text-slate-600 font-bold w-1/2 text-right">{gan}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Footer Info */}
      <div className="w-full bg-slate-50/50 p-2 space-y-1.5 border-t border-slate-100 text-[10px]">
        <div className="flex justify-between items-center">
          <span className="text-slate-400">纳音</span>
          <span className="text-violet-600 font-medium truncate max-w-[60px]">{data.naYin}</span>
        </div>

        {/* Chang Sheng Logic: DayMaster vs SelfSitting */}
        <div className="flex justify-between items-center">
          <span className="text-slate-400 text-[9px] scale-95 origin-left" title="日干长生 (运)">运·长生</span>
          <span className="text-slate-700 font-medium">{data.xingYun}</span>
        </div>
        <div className="flex justify-between items-center">
          <span className="text-slate-400 text-[9px] scale-95 origin-left" title="自坐长生 (坐)">坐·长生</span>
          <span className="text-slate-500">{data.selfXingYun}</span>
        </div>

        {data.kongWang && (
          <div className="flex justify-center mt-1">
            <span className="bg-red-50 text-red-400 px-2 py-0.5 rounded-full text-[9px] font-mono border border-red-100">
              空亡
            </span>
          </div>
        )}
      </div>
    </div>
  );
};

export const BaziChartDisplay: React.FC<Props> = ({ chart }) => {
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);
  const zhiRefs = useRef<(HTMLDivElement | null)[]>([]);
  const containerRef = useRef<HTMLDivElement>(null);
  const [lines, setLines] = useState<{ x1: number, y1: number, x2: number, y2: number, type: string, label: string }[]>([]);

  const pillars = [chart.pillars.year, chart.pillars.month, chart.pillars.day, chart.pillars.hour];
  const titles = ['年柱', '月柱', '日柱', '时柱'];

  useEffect(() => {
    if (hoveredIndex === null || !containerRef.current) {
      setLines([]);
      return;
    }

    const updateLines = () => {
      if (!containerRef.current || hoveredIndex === null) return;

      const containerRect = containerRef.current.getBoundingClientRect();
      const sourceEl = zhiRefs.current[hoveredIndex];
      if (!sourceEl) return;

      const sourceRect = sourceEl.getBoundingClientRect();

      // Calculate relative to container
      const sourceX = sourceRect.left - containerRect.left + sourceRect.width / 2;
      const sourceY = sourceRect.top - containerRect.top + sourceRect.height / 2;

      const newLines: any[] = [];

      pillars.forEach((pillar, idx) => {
        if (idx === hoveredIndex) return;

        const targetEl = zhiRefs.current[idx];
        if (!targetEl) return;

        const rel = getRelationship(pillars[hoveredIndex].zhi, pillar.zhi);
        if (rel.type) {
          const targetRect = targetEl.getBoundingClientRect();
          const targetX = targetRect.left - containerRect.left + targetRect.width / 2;
          const targetY = targetRect.top - containerRect.top + targetRect.height / 2;

          newLines.push({
            x1: sourceX,
            y1: sourceY,
            x2: targetX,
            y2: targetY,
            type: rel.type,
            label: rel.label
          });
        }
      });
      setLines(newLines);
    };

    updateLines();
    window.addEventListener('resize', updateLines);
    return () => window.removeEventListener('resize', updateLines);
  }, [hoveredIndex, chart]);

  return (
    <div className="space-y-6 animate-in fade-in zoom-in-95 duration-500">
      {/* Header Meta Info */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3">
        {[
          { label: '公历', value: chart.meta.solarDate },
          { label: '农历', value: chart.meta.lunarDate },
          { label: '真太阳时', value: chart.meta.trueSolarTime, highlight: true },
          { label: '起运', value: chart.meta.qiYunInfo, highlight: true },
          { label: '造/肖', value: `${chart.meta.gender} / ${chart.meta.sign}` }
        ].map((item, i) => (
          <div key={i} className="bg-white/60 p-3 rounded-xl border border-slate-100 shadow-sm flex flex-col hover:bg-white transition-colors">
            <span className="text-[10px] text-slate-400 uppercase tracking-wider mb-1">{item.label}</span>
            <span className={`font-medium text-xs sm:text-sm ${item.highlight ? 'text-violet-600' : 'text-slate-700'}`}>
              {item.value || '-'}
            </span>
          </div>
        ))}
      </div>

      {/* Three Palaces / Hidden Info */}
      <div className="flex flex-wrap gap-2 justify-center sm:justify-between p-3 bg-slate-50/80 rounded-xl border border-slate-100/80 backdrop-blur-sm">
        {[
          { label: '胎元', value: chart.hidden.taiYuan },
          { label: '命宫', value: chart.hidden.mingGong },
          { label: '身宫', value: chart.hidden.shenGong }
        ].map((item, i) => (
          <div key={i} className="flex items-center gap-2 px-3 py-1 bg-white rounded-lg shadow-sm border border-slate-100">
            <span className="text-[10px] text-slate-400 uppercase">{item.label}</span>
            <span className="font-serif font-bold text-slate-700">{item.value}</span>
          </div>
        ))}
      </div>

      {/* The Bazi Matrix */}
      <div className="relative p-2" ref={containerRef}>
        {/* SVG Overlay for Connections */}
        <svg className="absolute inset-0 pointer-events-none z-30 w-full h-full overflow-visible">
          <defs>
            <marker id="arrowhead-clash" markerWidth="6" markerHeight="4" refX="5" refY="2" orient="auto">
              <path d="M0,0 L6,2 L0,4 z" fill="#f43f5e" />
            </marker>
            <marker id="arrowhead-combine" markerWidth="6" markerHeight="4" refX="5" refY="2" orient="auto">
              <path d="M0,0 L6,2 L0,4 z" fill="#10b981" />
            </marker>
          </defs>
          {lines.map((line, idx) => {
            const isClash = line.type === 'clash';
            const color = isClash ? '#f43f5e' : '#10b981'; // rose-500 : emerald-500
            const midX = (line.x1 + line.x2) / 2;
            const midY = (line.y1 + line.y2) / 2;

            // Curve the line slightly for better visuals
            const curveOffset = 30;
            const pathData = `M${line.x1},${line.y1} Q${midX},${midY - curveOffset} ${line.x2},${line.y2}`;

            return (
              <g key={idx} className="drop-shadow-md">
                <path
                  d={pathData}
                  fill="none"
                  stroke={color}
                  strokeWidth="2.5"
                  strokeDasharray={isClash ? "6,4" : "0"}
                  strokeLinecap="round"
                  opacity="0.9"
                  markerEnd={`url(#arrowhead-${line.type})`}
                />
                {/* Badge for Relationship Type */}
                <g transform={`translate(${midX},${midY - curveOffset / 2})`}>
                  <rect x="-12" y="-10" width="24" height="20" rx="4" fill="white" stroke={color} strokeWidth="1.5" />
                  <text
                    dy="0.32em"
                    fill={color}
                    fontSize="11"
                    fontWeight="bold"
                    textAnchor="middle"
                  >
                    {line.label}
                  </text>
                </g>
              </g>
            );
          })}
        </svg>

        <div className="grid grid-cols-4 gap-2 sm:gap-4 select-none">
          {pillars.map((pillar, idx) => (
            <PillarCard
              key={idx}
              title={titles[idx]}
              data={pillar}
              highlight={idx === 2} // Day pillar
              setZhiRef={(el) => zhiRefs.current[idx] = el}
              onHover={(hover) => setHoveredIndex(hover ? idx : null)}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

// tianji-mp/src/components/BaziChart.vue
<template>
  <view class="space-y-6 animate-in" v-if="hasChart">
    <!-- Header Meta Info -->
    <view class="meta-grid">
      <view class="meta-item" v-for="(item, i) in metaItems" :key="i">
        <text class="meta-label">{{ item.label }}</text>
        <text :class="['meta-value', item.highlight ? 'highlight' : '']">{{ item.value || '-' }}</text>
      </view>
    </view>

    <!-- Three Palaces -->
    <view class="palaces-row">
      <view class="palace-item" v-for="(item, i) in palaceItems" :key="i">
        <text class="palace-label">{{ item.label }}</text>
        <text class="palace-value">{{ item.value }}</text>
      </view>
    </view>

    <!-- Bazi Matrix -->
    <view class="bazi-container" id="bazi-container">
      <!-- Pillars -->
      <view v-if="pillars.length" class="pillars-grid">
        <view 
          v-for="(pillar, idx) in pillars" 
          :key="idx" 
          class="pillar-card"
          :class="{'highlight-pillar': idx === 2}"
          @click="handlePillarClick(idx)"
        >
          <view class="pillar-title" :class="idx === 2 ? 'title-highlight' : ''">{{ titles[idx] }}</view>
          
          <view class="pillar-content">
            <view class="god-text">{{ pillar.ganGod }}</view>
            <view class="stem-text">{{ pillar.gan }}</view>
            <view
              class="branch-text"
              :class="idx === 2 ? 'branch-highlight' : ''"
              :id="'pillar-zhi-' + idx"
            >
              {{ pillar.zhi }}
            </view>
            
            <view class="hidden-stems">
                <view v-for="(gan, hIdx) in pillar.hiddenGan" :key="hIdx" class="hidden-row">
                    <text class="hidden-god">{{ pillar.zhiGod[hIdx] || '-' }}</text>
                    <text class="hidden-gan">{{ gan }}</text>
                </view>
            </view>
          </view>

          <view class="pillar-footer">
            <view class="footer-row">
              <text class="footer-label">纳音</text>
              <text class="nayin-text">{{ pillar.naYin }}</text>
            </view>
             <view class="footer-row">
              <text class="footer-label">运·长生</text>
              <text class="footer-val">{{ pillar.xingYun }}</text>
            </view>
             <view class="footer-row">
              <text class="footer-label">坐·长生</text>
              <text class="footer-val">{{ pillar.selfXingYun }}</text>
            </view>
            <view v-if="pillar.kongWang" class="kongwang-tag">空亡</view>
          </view>
        </view>
      </view>
      <view v-else class="pillars-empty">
        四柱数据为空，请检查命盘计算结果。
      </view>
      
      <!-- Relationships Canvas -->
      <canvas
        v-if="canvasWidth > 0 && canvasHeight > 0"
        canvas-id="relationCanvas"
        id="relationCanvas"
        class="relation-canvas"
        :style="{ width: canvasWidth + 'px', height: canvasHeight + 'px' }"
        :width="canvasWidth"
        :height="canvasHeight"
      ></canvas>

    </view>
  </view>
  <view v-else class="pillars-empty">
    命盘数据为空，请检查档案信息或重新生成。
  </view>
</template>

<script setup lang="ts">
import { computed, ref, nextTick, getCurrentInstance, watch } from 'vue';
import type { BaziChart } from '@/models';

const props = defineProps<{
  chart: BaziChart
}>();

const chartValue = computed(() => {
    const maybeRef = props.chart as any;
    return maybeRef && maybeRef.value ? maybeRef.value : props.chart;
});

const hasChart = computed(() => !!chartValue.value && !!chartValue.value.pillars);

const pillars = computed(() => {
    if(!chartValue.value) return [];
    return [
        chartValue.value.pillars.year,
        chartValue.value.pillars.month,
        chartValue.value.pillars.day,
        chartValue.value.pillars.hour
    ];
});

const titles = ['年柱', '月柱', '日柱', '时柱'];

// Meta Info
const metaItems = computed(() => {
    if (!chartValue.value) return [];
    return [
        { label: '公历', value: chartValue.value.meta.solarDate },
        { label: '农历', value: chartValue.value.meta.lunarDate },
        { label: '真太阳时', value: chartValue.value.meta.trueSolarTime, highlight: true },
        { label: '起运', value: chartValue.value.meta.qiYunInfo, highlight: true },
        { label: '性别/生肖', value: `${chartValue.value.meta.gender} / ${chartValue.value.meta.sign}` }
    ];
});

// Palaces
const palaceItems = computed(() => {
    if (!chartValue.value) return [];
    return [
        { label: '胎元', value: chartValue.value.hidden.taiYuan },
        { label: '命宫', value: chartValue.value.hidden.mingGong },
        { label: '身宫', value: chartValue.value.hidden.shenGong }
    ];
});

// Relationship Logic
const ZHI_RELATIONS: Record<string, { clash: string[], combine: string[] }> = {
  '子': { clash: ['午'], combine: ['丑'] },
  '丑': { clash: ['未'], combine: ['子'] },
  '寅': { clash: ['申'], combine: ['亥'] },
  '卯': { clash: ['酉'], combine: ['戌'] },
  '辰': { clash: ['戌'], combine: ['酉'] },
  '巳': { clash: ['亥'], combine: ['申'] },
  '午': { clash: ['子'], combine: ['未'] },
  '未': { clash: ['丑'], combine: ['午'] },
  '申': { clash: ['寅'], combine: ['巳'] },
  '酉': { clash: ['卯'], combine: ['辰'] },
  '戌': { clash: ['辰'], combine: ['卯'] },
  '亥': { clash: ['巳'], combine: ['寅'] },
};

const canvasWidth = ref(0);
const canvasHeight = ref(0);
const clearTimer = ref<number | null>(null);
const instance = getCurrentInstance();

const getRelationship = (z1: string, z2: string): { type: 'clash' | 'combine' | null; label: string } => {
    const rel = ZHI_RELATIONS[z1];
    if (rel?.clash.includes(z2)) return { type: 'clash', label: '冲' };
    if (rel?.combine.includes(z2)) return { type: 'combine', label: '合' };
    return { type: null, label: '' };
};

const handlePillarClick = (idx: number) => {
    drawRelations(idx);
};

const clearCanvas = () => {
    if (!instance?.proxy || canvasWidth.value <= 0 || canvasHeight.value <= 0) return;
    const ctx = uni.createCanvasContext('relationCanvas', instance.proxy);
    if (!ctx) return;
    ctx.clearRect(0, 0, canvasWidth.value, canvasHeight.value);
    ctx.draw();
};

const drawRelations = async (sourceIndex: number) => {
    if (!instance?.proxy || pillars.value.length === 0) return;
    await nextTick();

    const query = uni.createSelectorQuery().in(instance.proxy);
    query.select('#bazi-container').boundingClientRect();
    pillars.value.forEach((_, i) => {
        query.select(`#pillar-zhi-${i}`).boundingClientRect();
    });

    query.exec((res: any[]) => {
        const container = res[0];
        if (!container) return;

        const rects = res.slice(1);
        if (rects.some((r: any) => !r)) return;

        canvasWidth.value = Math.round(container.width);
        canvasHeight.value = Math.round(container.height);

        const ctx = uni.createCanvasContext('relationCanvas', instance.proxy);
        ctx.clearRect(0, 0, canvasWidth.value, canvasHeight.value);

        const sourceRect = rects[sourceIndex];
        const sourceX = sourceRect.left - container.left + sourceRect.width / 2;
        const sourceY = sourceRect.top - container.top + sourceRect.height / 2;

        rects.forEach((targetRect: any, idx: number) => {
            if (idx === sourceIndex) return;

            const rel = getRelationship(pillars.value[sourceIndex].zhi, pillars.value[idx].zhi);
            if (!rel.type) return;

            const targetX = targetRect.left - container.left + targetRect.width / 2;
            const targetY = targetRect.top - container.top + targetRect.height / 2;
            const midX = (sourceX + targetX) / 2;
            const midY = (sourceY + targetY) / 2;
            const curveOffset = 16;
            const controlY = midY - curveOffset;

            const color = rel.type === 'clash' ? '#f43f5e' : '#10b981';
            if (typeof (ctx as any).setLineDash === 'function') {
                (ctx as any).setLineDash(rel.type === 'clash' ? [6, 4] : []);
            }
            ctx.setStrokeStyle(color);
            ctx.setLineWidth(2);
            ctx.beginPath();
            ctx.moveTo(sourceX, sourceY);
            ctx.quadraticCurveTo(midX, controlY, targetX, targetY);
            ctx.stroke();

            // Arrowhead
            const angle = Math.atan2(targetY - controlY, targetX - midX);
            const headLen = 8;
            const arrowX = targetX - Math.cos(angle) * 6;
            const arrowY = targetY - Math.sin(angle) * 6;
            ctx.beginPath();
            ctx.setFillStyle(color);
            ctx.moveTo(targetX, targetY);
            ctx.lineTo(arrowX - Math.sin(angle) * headLen / 2, arrowY + Math.cos(angle) * headLen / 2);
            ctx.lineTo(arrowX + Math.sin(angle) * headLen / 2, arrowY - Math.cos(angle) * headLen / 2);
            ctx.closePath();
            ctx.fill();

            // Label
            const labelW = 24;
            const labelH = 16;
            ctx.setFillStyle('#ffffff');
            ctx.setStrokeStyle(color);
            ctx.setLineWidth(1);
            ctx.fillRect(midX - labelW / 2, controlY - labelH / 2, labelW, labelH);
            ctx.strokeRect(midX - labelW / 2, controlY - labelH / 2, labelW, labelH);
            ctx.setFillStyle(color);
            ctx.setFontSize(10);
            ctx.setTextAlign('center');
            ctx.setTextBaseline('middle');
            ctx.fillText(rel.label, midX, controlY);
        });

        ctx.draw();
    });

    if (clearTimer.value) clearTimeout(clearTimer.value);
    clearTimer.value = Number(setTimeout(() => {
        clearCanvas();
    }, 3000));
};

watch(() => props.chart, () => {
    clearCanvas();
});

</script>

<style scoped>
.space-y-6 { margin-bottom: 24rpx; }
.animate-in { animation: fadeIn 0.5s forwards; }
@keyframes fadeIn { to { opacity: 1; } }

.meta-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 12rpx;
    margin-bottom: 24rpx;
}
.meta-item {
    background: rgba(255,255,255,0.6);
    padding: 12rpx;
    border-radius: 12rpx;
    border: 1px solid #f1f5f9;
    flex: 1 1 40%;
    display: flex;
    flex-direction: column;
}
.meta-label { font-size: 20rpx; color: #94a3b8; margin-bottom: 4rpx; }
.meta-value { font-size: 24rpx; color: #334155; font-weight: 500; }
.highlight { color: #7c3aed; }

.palaces-row {
    display: flex;
    justify-content: space-between;
    padding: 12rpx;
    background: #f8fafc;
    border-radius: 12rpx;
    margin-bottom: 24rpx;
}
.palace-item { display: flex; align-items: center; gap: 8rpx; }
.palace-label { font-size: 20rpx; color: #94a3b8; }
.palace-value { font-weight: bold; color: #334155; }

.bazi-container { position: relative; padding: 8rpx; }

.pillars-grid {
    display: flex;
    justify-content: space-between;
    gap: 8rpx;
}

.pillar-card {
    flex: 1;
    background: #fff;
    border-radius: 12rpx;
    overflow: hidden;
    box-shadow: 0 2rpx 8rpx rgba(0,0,0,0.04);
    display: flex;
    flex-direction: column;
    align-items: center;
    border: 1px solid #cbd5e1;
}

.highlight-pillar {
    border: 2px solid #a78bfa;
    box-shadow: 0 0 10rpx rgba(139, 92, 246, 0.2);
}

.pillar-title {
    width: 100%;
    text-align: center;
    font-size: 20rpx;
    padding: 6rpx 0;
    font-weight: bold;
    background: #f8fafc;
    color: #64748b;
}

.title-highlight { background: #f5f3ff; color: #6d28d9; }

.pillar-content {
    padding: 12rpx 8rpx;
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
}

.god-text { font-size: 20rpx; color: #94a3b8; height: 32rpx; }
.stem-text { font-size: 36rpx; font-weight: 900; color: #1e293b; line-height: 1; margin-bottom: 8rpx; }
.branch-text { 
    font-size: 36rpx; 
    font-weight: 900; 
    color: #1e293b; 
    line-height: 1; 
    padding: 8rpx 0; 
    width: 100%; 
    text-align: center; 
    border-radius: 8rpx; 
}
.branch-highlight { color: #4c1d95; background: #f5f3ff; }

.hidden-stems { 
    margin-top: 8rpx; 
    width: 100%; 
    border-top: 1px solid #f1f5f9; 
    padding-top: 8rpx; 
}
.hidden-row { display: flex; justify-content: space-between; font-size: 18rpx; }
.hidden-god { color: #94a3b8; transform: scale(0.9); transform-origin: left; }
.hidden-gan { font-weight: bold; color: #475569; }

.pillar-footer {
    width: 100%;
    background: #f8fafc;
    padding: 6rpx;
    border-top: 1px solid #e2e8f0;
}
.footer-row { display: flex; justify-content: space-between; font-size: 18rpx; margin-bottom: 2rpx; }
.footer-label { color: #94a3b8; transform: scale(0.85); transform-origin: left; }
.footer-val { color: #334155; transform: scale(0.9); transform-origin: right; }
.nayin-text { color: #7c3aed; width: 80rpx; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-align: right; transform: scale(0.9); transform-origin: right; }

.kongwang-tag {
    text-align: center;
    font-size: 18rpx;
    color: #f87171;
    background: #fef2f2;
    border: 1px solid #fee2e2;
    border-radius: 999rpx;
    margin-top: 4rpx;
}

.relation-canvas {
    position: absolute;
    inset: 0;
    z-index: 40;
    pointer-events: none;
}
.pillars-empty {
    padding: 16rpx;
    text-align: center;
    color: #94a3b8;
    font-size: 24rpx;
}
</style>
