// components/ElementalChart.tsx
import React from 'react';
import { ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, Cell, PieChart, Pie, Tooltip as RechartsTooltip } from 'recharts';
import { BaziChart } from '../types';
import { Shield, Zap, TrendingUp, AlertTriangle, Activity, Droplets, Flame, Mountain, Wind, Disc } from 'lucide-react';

interface Props {
  wuxing: BaziChart['wuxing'];
}

const ELEMENT_ICONS: Record<string, React.ReactNode> = {
  '木': <Wind size={16} className="text-emerald-500" />,
  '火': <Flame size={16} className="text-rose-500" />,
  '土': <Mountain size={16} className="text-amber-500" />,
  '金': <Disc size={16} className="text-slate-400" />,
  '水': <Droplets size={16} className="text-blue-500" />
};

export const ElementalChart: React.FC<Props> = ({ wuxing }) => {
  const details = wuxing.details;

  // Fallback if details are missing (backward compatibility)
  if (!details) {
    return (
      <div className="p-4 bg-white rounded-lg text-center text-slate-400">
        暂无详细分析数据，请刷新重试。
      </div>
    );
  }

  // --- Dynamic Scaling Logic ---
  const maxScore = Math.max(...wuxing.scores.map(s => s.value), 10); // Minimum 10 to avoid div/0 or tiny scale
  const totalScore = wuxing.scores.reduce((a, b) => a + b.value, 0) || 1;
  const chartDomainMax = maxScore * 1.2; // Scale charts so max element is ~80% of radius/bar

  // Gauge Angle Calculation (-90 to 90 degrees)
  const gaugeAngle = (details.percentage / 100) * 180 - 90;

  const getStrengthColor = (p: number) => {
    if (p >= 55) return 'text-purple-600 bg-purple-50 border-purple-200';
    if (p < 35) return 'text-amber-600 bg-amber-50 border-amber-200';
    return 'text-emerald-600 bg-emerald-50 border-emerald-200';
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-700">

      {/* 1. Top Cards Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

        {/* Card 1: DM Strength Gauge */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 flex flex-col items-center justify-between relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-amber-400 via-emerald-400 to-purple-500 opacity-50"></div>

          <div className="flex items-center gap-2 mb-4">
            <Activity size={18} className="text-slate-400" />
            <h3 className="font-bold text-slate-700">日元旺衰</h3>
          </div>

          {/* Gauge Visual */}
          <div className="relative w-48 h-24 mt-2 mb-6">
            <div className="absolute w-full h-full rounded-tl-full rounded-tr-full bg-slate-100 border-t-[16px] border-l-[16px] border-r-[16px] border-slate-100 box-content -left-4 -top-4"></div>
            <div className="absolute bottom-0 left-[10%] w-[80%] h-[180%] border-t-[16px] border-l-[16px] border-r-[16px] border-transparent border-t-emerald-200 rounded-full opacity-30"></div>
            <div
              className="absolute bottom-0 left-1/2 w-1 h-[calc(100%-10px)] bg-slate-800 origin-bottom transition-transform duration-1000 ease-out z-10 rounded-full shadow-lg"
              style={{ transform: `translateX(-50%) rotate(${gaugeAngle}deg)` }}
            >
              <div className="absolute -top-1 left-1/2 -translate-x-1/2 w-4 h-4 bg-slate-800 rounded-full border-2 border-white"></div>
            </div>
            <div className="absolute bottom-0 left-1/2 w-4 h-2 -translate-x-1/2 bg-slate-800 rounded-t-full z-20"></div>
          </div>

          <div className="text-center">
            <div className="text-3xl font-serif font-black text-slate-800">
              {details.percentage}<span className="text-sm font-sans text-slate-400 font-normal">%</span>
            </div>
            <div className={`mt-2 px-3 py-1 rounded-full text-xs font-bold border ${getStrengthColor(details.percentage)}`}>
              {details.strength}
            </div>
          </div>
          <p className="text-[10px] text-slate-400 mt-2">同党 vs 异党能量比</p>
        </div>

        {/* Card 2: Radar Balance */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-4">
          <h3 className="font-bold text-slate-700 text-center mb-2 flex justify-center items-center gap-2">
            <TrendingUp size={16} className="text-slate-400" /> 五行分布
          </h3>
          <div className="h-[200px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart cx="50%" cy="50%" outerRadius="65%" data={wuxing.scores}>
                <PolarGrid stroke="#e2e8f0" />
                <PolarAngleAxis dataKey="name" tick={{ fontSize: 12, fill: '#64748b' }} />
                <PolarRadiusAxis angle={30} domain={[0, chartDomainMax]} tick={false} />
                <Radar
                  name="能量"
                  dataKey="value"
                  stroke="#8b5cf6"
                  fill="#8b5cf6"
                  fillOpacity={0.4}
                />
                <RechartsTooltip
                  contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                  itemStyle={{ fontSize: '12px', color: '#4c1d95', fontWeight: 'bold' }}
                />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Card 3: Yong Shen (Useful God) */}
        <div className="bg-gradient-to-br from-violet-600 to-indigo-700 rounded-2xl shadow-lg shadow-violet-200 text-white p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-4 opacity-90">
              <Shield size={18} />
              <h3 className="font-bold">喜用神建议</h3>
            </div>
            <div className="text-2xl font-bold leading-relaxed tracking-wide">
              {details.yongShen.split('/').map((s, i) => (
                <span key={i} className="inline-block mr-2 mb-2 px-3 py-1 bg-white/20 rounded-lg text-sm backdrop-blur-sm border border-white/10">
                  {s.trim()}
                </span>
              ))}
            </div>
          </div>
          <div className="mt-4 pt-4 border-t border-white/20 text-xs opacity-75 leading-relaxed">
            <p>建议佩戴或多亲近上述五行对应的颜色、方位或行业，以平衡命局能量。</p>
          </div>
        </div>
      </div>

      {/* 2. Detailed Breakdown Row */}
      <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6">
        <h3 className="font-bold text-slate-700 mb-6 flex items-center gap-2">
          <Zap size={18} className="text-amber-500" />
          五行能量量化表
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-5 gap-6">
          {wuxing.scores.map((score) => {
            // Visualize relative to the strongest element (so max bar is ~80-90% full)
            const visualPercent = Math.min(100, (score.value / chartDomainMax) * 100);
            const realRatio = Math.round((score.value / totalScore) * 100);

            return (
              <div key={score.name} className="flex flex-col gap-2">
                <div className="flex justify-between items-end">
                  <span className="flex items-center gap-1 font-bold text-slate-700">
                    {ELEMENT_ICONS[score.name]}
                    {score.name}
                  </span>
                  <div className="text-right">
                    <span className="text-2xl font-serif font-black text-slate-800 leading-none">{score.value}</span>
                    <span className="text-[10px] text-slate-400 ml-1 font-medium">{realRatio}%</span>
                  </div>
                </div>
                {/* Progress Bar */}
                <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden">
                  <div
                    className="h-full rounded-full transition-all duration-1000"
                    style={{ width: `${visualPercent}%`, backgroundColor: score.color }}
                  ></div>
                </div>
                <div className="text-[10px] text-slate-400 text-right">
                  能量强度
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* 3. Text Analysis */}
      <div className="bg-slate-50 rounded-2xl border border-slate-100 p-6">
        <div className="flex gap-4">
          <div className="shrink-0 mt-1">
            <div className="w-10 h-10 rounded-full bg-white flex items-center justify-center shadow-sm border border-slate-100 text-violet-600">
              <Activity size={20} />
            </div>
          </div>
          <div className="space-y-2">
            <h3 className="font-bold text-slate-800">AI 综合评语</h3>
            <p className="text-slate-600 leading-relaxed text-sm whitespace-pre-wrap">
              {wuxing.summary.replace(/建议喜用神：.*$/, '')}
              {/* Removing the duplicate suggestion line since we have cards for it */}
            </p>
            {details.strength !== '中和' && (
              <div className="flex items-center gap-2 text-xs text-amber-600 bg-amber-50 px-3 py-2 rounded-lg border border-amber-100 w-fit mt-2">
                <AlertTriangle size={12} />
                <span>
                  {details.strength === '偏旺' ? '日主过旺，宜克泄耗，忌印比。' : '日主偏弱，宜印比帮身，忌克泄。'}
                </span>
              </div>
            )}
          </div>
        </div>
      </div>

    </div>
  );
};

// tianji-mp/src/components/ElementalChart.vue
<template>
  <view class="elemental-container animate-fade-in">
    
    <!-- Top Row -->
    <view class="cards-grid">
        
        <!-- DM Strength (Gauge) -->
        <view class="card gauge-card">
            <view class="card-header">
                <text class="icon">📊</text>
                <text class="title">日元旺衰</text>
            </view>
            
            <view class="gauge-wrapper">
                 <view class="gauge-arc-bg"></view>
                 <view class="gauge-needle" :style="{ transform: `rotate(${gaugeAngle}deg)` }"></view>
                 <view class="gauge-cover"></view>
            </view>
            
            <view class="gauge-text">
                <text class="percent">{{ details.percentage }}<text class="unit">%</text></text>
                <view :class="['strength-tag', strengthClass]">{{ details.strength }}</view>
            </view>
            <text class="subtext">同党 vs 异党能量比</text>
        </view>
        
        <!-- Radar Balance -->
        <view class="card radar-card">
            <view class="card-header">
                <text class="icon">📡</text>
                <text class="title">五行分布</text>
            </view>
            <view class="radar-wrapper">
                <canvas
                  canvas-id="wuxingRadar"
                  id="wuxingRadar"
                  class="radar-canvas"
                  :style="{ width: radarSize + 'px', height: radarSize + 'px' }"
                  :width="radarSize"
                  :height="radarSize"
                ></canvas>
            </view>
        </view>

        <!-- Yong Shen -->
        <view class="card yong-shen-card">
            <view class="ys-header">
                <text>🛡 喜用神建议</text>
            </view>
            <view class="ys-content">
                <view v-for="(s, i) in yongShenList" :key="i" class="ys-tag">
                    {{ s }}
                </view>
            </view>
            <view class="ys-footer">
                建议亲近上述五行对应的颜色、方位。
            </view>
        </view>
        
    </view>

    <!-- Energy Bars -->
    <view class="card bars-card">
        <view class="card-header">
            <text class="icon">⚡</text>
            <text class="title">五行能量量化</text>
        </view>
        
        <view class="bars-list">
            <view v-for="score in wuxing.scores" :key="score.name" class="bar-item">
                <view class="bar-top">
                    <view class="bar-label">
                        <text class="bar-icon" :style="{color: score.color}">●</text>
                        <text>{{ score.name }}</text>
                    </view>
                    <view class="bar-val-group">
                         <text class="bar-num">{{ score.value }}</text>
                         <text class="bar-percent">{{ getRealRatio(score.value) }}%</text>
                    </view>
                </view>
                <view class="progress-bg">
                    <view class="progress-fill" :style="{ width: getVisualPercent(score.value) + '%', backgroundColor: score.color }"></view>
                </view>
            </view>
        </view>
    </view>

    <!-- Analysis Text -->
    <view class="card text-card">
        <view class="text-content">
            <view class="ai-icon-box">
                <text>📝</text>
            </view>
            <view class="ai-text-box">
                <view class="ai-title">AI 综合评语</view>
                <text class="ai-desc">{{ summaryClean }}</text>
                <view v-if="details.strength !== '中和'" class="ai-alert">
                    <text>⚠ {{ details.strength === '偏旺' ? '日主过旺，宜克泄耗，忌印比。' : '日主偏弱，宜印比帮身，忌克泄。' }}</text>
                </view>
            </view>
        </view>
    </view>

  </view>
 </template>

<script setup lang="ts">
import { computed, ref, onMounted, watch, nextTick, getCurrentInstance } from 'vue';
import type { BaziChart } from '@/models';

const props = defineProps<{
  wuxing: BaziChart['wuxing']
}>();

const radarSize = ref(220);
const instance = getCurrentInstance();

const details = computed(() => props.wuxing.details || {
    percentage: 50,
    strength: '中和',
    yongShen: '无',
    sameParty: 50,
    otherParty: 50
});

const gaugeAngle = computed(() => {
    return (details.value.percentage / 100) * 180 - 90;
});

const strengthClass = computed(() => {
    const p = details.value.percentage;
    if (p >= 55) return 'strong';
    if (p < 35) return 'weak';
    return 'balanced';
});

const yongShenList = computed(() => {
    return details.value.yongShen.split('/').map(s => s.trim());
});

const summaryClean = computed(() => {
    return props.wuxing.summary.replace(/建议喜用神：.*$/, '');
});

// Helpers for bars
const maxScore = computed(() => Math.max(...props.wuxing.scores.map(s => s.value), 10));
const totalScore = computed(() => props.wuxing.scores.reduce((a, b) => a + b.value, 0) || 1);
const chartDomainMax = computed(() => maxScore.value * 1.2);

const getVisualPercent = (val: number) => {
    return Math.min(100, (val / chartDomainMax.value) * 100);
};
const getRealRatio = (val: number) => {
    return Math.round((val / totalScore.value) * 100);
};

const updateRadarSize = () => {
    const sys = uni.getSystemInfoSync();
    const maxSize = Math.min(260, sys.windowWidth - 80);
    radarSize.value = Math.max(180, maxSize);
};

const drawPolygon = (ctx: UniApp.CanvasContext, points: { x: number; y: number }[]) => {
    if (points.length === 0) return;
    ctx.beginPath();
    ctx.moveTo(points[0].x, points[0].y);
    points.slice(1).forEach(p => ctx.lineTo(p.x, p.y));
    ctx.closePath();
    ctx.stroke();
};

const drawRadar = async () => {
    if (!instance?.proxy) return;
    await nextTick();

    const size = radarSize.value;
    const ctx = uni.createCanvasContext('wuxingRadar', instance.proxy);
    ctx.clearRect(0, 0, size, size);

    const center = size / 2;
    const radius = size * 0.32;
    const angles = props.wuxing.scores.map((_, i) => (-90 + i * 72) * Math.PI / 180);

    // Grid rings
    ctx.setStrokeStyle('#e2e8f0');
    ctx.setLineWidth(1);
    for (let r = 1; r <= 4; r++) {
        const ringRadius = radius * (r / 4);
        const ringPoints = angles.map(a => ({
            x: center + ringRadius * Math.cos(a),
            y: center + ringRadius * Math.sin(a),
        }));
        drawPolygon(ctx, ringPoints);
    }

    // Axis lines
    angles.forEach(a => {
        ctx.beginPath();
        ctx.moveTo(center, center);
        ctx.lineTo(center + radius * Math.cos(a), center + radius * Math.sin(a));
        ctx.stroke();
    });

    // Data polygon
    const points = props.wuxing.scores.map((score, i) => {
        const ratio = Math.min(1, score.value / chartDomainMax.value);
        return {
            x: center + radius * ratio * Math.cos(angles[i]),
            y: center + radius * ratio * Math.sin(angles[i]),
        };
    });
    ctx.setFillStyle('rgba(139, 92, 246, 0.35)');
    ctx.setStrokeStyle('#8b5cf6');
    ctx.setLineWidth(2);
    ctx.beginPath();
    ctx.moveTo(points[0].x, points[0].y);
    points.slice(1).forEach(p => ctx.lineTo(p.x, p.y));
    ctx.closePath();
    ctx.fill();
    ctx.stroke();

    // Points
    points.forEach(p => {
        ctx.beginPath();
        ctx.setFillStyle('#8b5cf6');
        ctx.arc(p.x, p.y, 3, 0, 2 * Math.PI);
        ctx.fill();
    });

    // Labels
    ctx.setFontSize(10);
    ctx.setFillStyle('#64748b');
    ctx.setTextAlign('center');
    ctx.setTextBaseline('middle');
    const labelRadius = radius + 14;
    props.wuxing.scores.forEach((score, i) => {
        const lx = center + labelRadius * Math.cos(angles[i]);
        const ly = center + labelRadius * Math.sin(angles[i]);
        ctx.fillText(score.name, lx, ly);
    });

    ctx.draw();
};

onMounted(() => {
    updateRadarSize();
    drawRadar();
});

watch(() => props.wuxing.scores, () => {
    drawRadar();
}, { deep: true });

</script>

<style scoped>
.elemental-container {
    display: flex;
    flex-direction: column;
    gap: 24rpx;
}

.cards-grid {
    display: flex;
    flex-direction: column;
    gap: 24rpx;
}

.card {
    background: #fff;
    border-radius: 24rpx;
    padding: 24rpx;
    border: 1px solid #f1f5f9;
    box-shadow: 0 2rpx 4rpx rgba(0,0,0,0.02);
}

.card-header {
    display: flex;
    align-items: center;
    gap: 12rpx;
    margin-bottom: 24rpx;
}
.title { font-weight: bold; color: #334155; font-size: 28rpx; }

/* Radar */
.radar-card { padding-bottom: 16rpx; }
.radar-wrapper { display: flex; justify-content: center; align-items: center; }
.radar-canvas { display: block; }

/* Gauge */
.gauge-card { align-items: center; text-align: center; }
.gauge-wrapper {
    position: relative;
    width: 300rpx;
    height: 150rpx;
    margin: 20rpx auto;
    overflow: hidden;
}
.gauge-arc-bg {
    width: 300rpx;
    height: 300rpx;
    background: #f1f5f9;
    border-radius: 50%;
}
.gauge-needle {
    position: absolute;
    bottom: 0;
    left: 50%;
    width: 6rpx;
    height: 140rpx;
    background: #334155;
    transform-origin: bottom center;
    transition: transform 1s ease-out;
}
.gauge-cover {
    position: absolute;
    bottom: -10rpx;
    left: 50%;
    transform: translateX(-50%);
    width: 20rpx;
    height: 20rpx;
    background: #334155;
    border-radius: 50%;
}

.gauge-text { margin-top: -20rpx; z-index: 10; position: relative; }
.percent { font-size: 48rpx; font-weight: 900; color: #1e293b; }
.unit { font-size: 24rpx; font-weight: normal; color: #94a3b8; }
.strength-tag { 
    display: inline-block; 
    font-size: 22rpx; 
    padding: 4rpx 16rpx; 
    border-radius: 999rpx; 
    margin-top: 8rpx;
    border: 1px solid;
}
.strong { color: #7c3aed; background: #f5f3ff; border-color: #ddd6fe; }
.weak { color: #d97706; background: #fffbeb; border-color: #fde68a; }
.balanced { color: #059669; background: #ecfdf5; border-color: #a7f3d0; }
.subtext { font-size: 20rpx; color: #94a3b8; margin-top: 12rpx; display: block; }

/* Yong Shen */
.yong-shen-card {
    background: linear-gradient(135deg, #7c3aed, #4338ca);
    color: white;
}
.ys-header { font-weight: bold; margin-bottom: 24rpx; opacity: 0.9; }
.ys-content { display: flex; flex-wrap: wrap; gap: 12rpx; margin-bottom: 24rpx; }
.ys-tag { 
    background: rgba(255,255,255,0.2); 
    padding: 8rpx 20rpx; 
    border-radius: 12rpx; 
    font-size: 28rpx; 
    border: 1px solid rgba(255,255,255,0.1);
}
.ys-footer { font-size: 22rpx; opacity: 0.7; border-top: 1px solid rgba(255,255,255,0.2); padding-top: 16rpx; }

/* Bars */
.bars-list { display: flex; flex-direction: column; gap: 24rpx; }
.bar-item { display: flex; flex-direction: column; gap: 8rpx; }
.bar-top { display: flex; justify-content: space-between; align-items: flex-end; }
.bar-label { display: flex; align-items: center; gap: 8rpx; font-size: 26rpx; font-weight: bold; color: #334155; }
.bar-val-group { text-align: right; }
.bar-num { font-size: 32rpx; font-weight: 900; color: #1e293b; margin-right: 4rpx; }
.bar-percent { font-size: 20rpx; color: #94a3b8; }
.progress-bg { height: 16rpx; background: #f1f5f9; border-radius: 999rpx; overflow: hidden; width: 100%; }
.progress-fill { height: 100%; border-radius: 999rpx; transition: width 1s ease-out; }

/* Text */
.text-content { display: flex; gap: 24rpx; }
.ai-icon-box { 
    width: 64rpx; height: 64rpx; 
    background: #fff; 
    border-radius: 50%; 
    display: flex; align-items: center; justify-content: center;
    border: 1px solid #f1f5f9;
}
.ai-text-box { flex: 1; }
.ai-title { font-weight: bold; color: #1e293b; margin-bottom: 8rpx; font-size: 28rpx; }
.ai-desc { font-size: 26rpx; color: #475569; line-height: 1.6; }
.ai-alert { margin-top: 16rpx; font-size: 24rpx; color: #d97706; background: #fffbeb; padding: 12rpx; border-radius: 12rpx; border: 1px solid #fde68a; }

.animate-fade-in { animation: fadeIn 0.8s ease-out; }
@keyframes fadeIn { from { opacity: 0; transform: translateY(20rpx); } to { opacity: 1; transform: translateY(0); } }
</style>
