// components/Timeline.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { BaziChart, DaYunData, LiuNianData } from '../types';
import { ChevronRight, TrendingUp, AlertCircle, Info, Sun, Moon, CalendarDays, ArrowRight, Compass, Clock, AlertTriangle, FileText, Bug, Sparkles, X, Loader2 } from 'lucide-react';
import { generateDailyGuide, DailyFortuneAPI } from '../services/aiService';

// --- CONSTANTS ---
const TIMING_MAP = ['23-01', '01-03', '03-05', '05-07', '07-09', '09-11', '11-13', '13-15', '15-17', '17-19', '19-21', '21-23'];
const SHI_CHEN = ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥'];

const DIRECTION_MAP: Record<string, string> = {
  '坎': '正北', '离': '正南', '震': '正东', '兑': '正西',
  '巽': '东南', '坤': '西南', '艮': '东北', '乾': '西北',
  '中': '中宫'
};

const TEN_GOD_INFO: Record<string, string> = {
  '比肩': '兄弟朋友助力，利合作盟友。但亦有竞争夺财之象，忌独断专行。',
  '劫财': '个性刚强，易冲动破财。虽然人脉广，但不利积蓄，需防小人争斗。',
  '食神': '福气临门，衣食无忧，心情舒畅。利于才艺创作与享受生活，诸事平顺。',
  '伤官': '思维活跃，才华横溢。但易变动工作或招惹口舌是非，利创新，忌傲慢。',
  '正财': '财运稳定，多为工薪正途之财。利积蓄守成，男命此时利于姻缘建立。',
  '偏财': '意外之财，投资获利机会多。财路宽广但也易大起大落，忌贪婪冒进。',
  '正官': '事业升迁，名誉地位提升。利于考试、求职与升职，女命利夫运。',
  '七杀': '压力增大，挑战与机遇并存。虽有魄力开拓但易生意外或疾病，宜守忌攻。',
  '正印': '贵人提拔，利名声学业。生活安逸稳定，少劳苦，多得长辈庇护。',
  '偏印': '思想独特，灵感丰富。利于冷门偏业或学术研究，但性格多孤僻，防孤独。'
};

// --- HELPER: Lightweight Markdown Renderer ---
const parseBold = (text: string) => {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part, j) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={j} className="text-violet-800 font-bold">{part.slice(2, -2)}</strong>;
    }
    return part;
  });
};

const SimpleMarkdown = ({ content }: { content: string }) => {
  if (!content) return null;
  return (
    <div className="space-y-2 font-sans text-sm text-slate-700 leading-relaxed">
      {content.split('\n').map((line, i) => {
        const trimmed = line.trim();
        if (!trimmed) return <div key={i} className="h-2"></div>;

        if (trimmed.startsWith('#')) {
          const text = trimmed.replace(/^#+\s*/, '');
          return <h4 key={i} className="text-violet-900 font-bold mt-4 mb-2 text-base">{text}</h4>;
        }

        if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          const text = trimmed.replace(/^[\-\*]\s*/, '');
          return (
            <div key={i} className="flex gap-2 items-start pl-1">
              <span className="text-violet-400 mt-1.5 text-[10px]">●</span>
              <span className="flex-1">{parseBold(text)}</span>
            </div>
          );
        }

        if (/^\d+\./.test(trimmed)) {
          return (
            <div key={i} className="pl-1 mb-1">
              {parseBold(trimmed)}
            </div>
          );
        }

        return <p key={i}>{parseBold(line)}</p>;
      })}
    </div>
  );
};


interface Props {
  chart: BaziChart | undefined | null;
}

export const Timeline: React.FC<Props> = ({ chart }) => {
  const [viewMode, setViewMode] = useState<'fortune' | 'dayun'>('fortune');
  const [selectedDaYunIndex, setSelectedDaYunIndex] = useState(0);
  const [selectedYear, setSelectedYear] = useState<LiuNianData | null>(null);
  const [now, setNow] = useState(new Date());

  // State for Lunar Data and Errors
  const [lunarData, setLunarData] = useState<any>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // AI State
  const [aiGuide, setAiGuide] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  // Safe ID Logic
  const sessionIdentity = useMemo(() => {
    if (!chart) return null;
    const todayStr = now.getFullYear() + '-' + (now.getMonth() + 1) + '-' + now.getDate();
    // Ultra-safe key generation based on chart metadata (Proxy for User ID)
    const safeId = (chart.meta.solarDate + chart.meta.gender).replace(/[^a-zA-Z0-9]/g, '');
    return { id: safeId, date: todayStr };
  }, [chart, now.getDate()]);

  // Load persistence via API Interface
  useEffect(() => {
    async function load() {
      if (sessionIdentity) {
        try {
          const stored = await DailyFortuneAPI.get(sessionIdentity.id, sessionIdentity.date);
          if (stored) {
            setAiGuide(stored);
          } else {
            setAiGuide(null);
          }
        } catch (e) {
          console.error("Failed to load daily guide", e);
        }
      }
    }
    load();
  }, [sessionIdentity]);

  const handleGenerateGuide = async () => {
    if (!lunarData || !chart || !sessionIdentity) return;

    setIsGenerating(true);
    try {
      const result = await generateDailyGuide(chart, lunarData);
      setAiGuide(result);
      // Save via Interface
      await DailyFortuneAPI.save(sessionIdentity.id, sessionIdentity.date, result);
    } catch (e) {
      console.error("AI Generation Error", e);
      alert("AI 服务暂时繁忙，请稍后再试。");
    } finally {
      setIsGenerating(false);
    }
  };

  // Effect to select current DaYun
  useEffect(() => {
    if (chart?.daYun) {
      const currentYear = new Date().getFullYear();
      const idx = chart.daYun.findIndex(dy => currentYear >= dy.startYear && currentYear <= (dy.startYear + 9));
      if (idx >= 0) {
        setSelectedDaYunIndex(idx);
        const yn = chart.daYun[idx].liuNian.find(y => y.year === currentYear);
        if (yn) setSelectedYear(yn);
      }
    }
  }, [chart]);

  useEffect(() => {
    const timer = setInterval(() => setNow(new Date()), 60000);
    return () => clearInterval(timer);
  }, []);

  // --- Safe Dynamic Import Engine for Lunar ---
  useEffect(() => {
    let mounted = true;

    const loadData = async () => {
      try {
        const module = await import('lunar-javascript');
        // @ts-ignore
        const Lunar = module.Lunar || module.default?.Lunar || module.default;

        if (!Lunar || typeof Lunar.fromDate !== 'function') {
          throw new Error(`Library loaded but Lunar entry not found.`);
        }

        const d = Lunar.fromDate(now);
        if (!d) throw new Error("Lunar.fromDate(now) returned null");

        const yi = typeof d.getDayYi === 'function' ? d.getDayYi() : [];
        const ji = typeof d.getDayJi === 'function' ? d.getDayJi() : [];
        const mapDir = (val: string) => DIRECTION_MAP[val] || val;

        const hoursList = [];
        const startOfDay = new Date(now);
        startOfDay.setHours(0, 0, 0, 0);

        for (let i = 0; i < 12; i++) {
          const h = i * 2;
          const tmpDate = new Date(startOfDay);
          tmpDate.setHours(h);
          const tmpLunar = Lunar.fromDate(tmpDate);

          const god = tmpLunar.getTimeTianShen ? tmpLunar.getTimeTianShen() : '';
          const luck = tmpLunar.getTimeTianShenLuck ? tmpLunar.getTimeTianShenLuck() : '';

          hoursList.push({
            zhi: SHI_CHEN[i],
            time: TIMING_MAP[i],
            god,
            luck
          });
        }

        const data = {
          ganZhiYear: d.getYearInGanZhi(),
          ganZhiMonth: d.getMonthInGanZhi(),
          ganZhiDay: d.getDayInGanZhi(),
          cnMonth: d.getMonthInChinese(),
          cnDay: d.getDayInChinese(),
          yi: yi,
          ji: ji,
          zhiXing: d.getZhiXing(),
          naYin: d.getDayNaYin ? d.getDayNaYin() : '',
          jiShen: d.getDayJiShen ? d.getDayJiShen() : [],
          xiongSha: d.getDayXiongSha ? d.getDayXiongSha() : [],
          wealthPos: mapDir(d.getPositionCai ? d.getPositionCai() : (d.getDayPositionCai ? d.getDayPositionCai() : '查无')),
          joyPos: mapDir(d.getPositionXi ? d.getPositionXi() : (d.getDayPositionXi ? d.getDayPositionXi() : '查无')),
          noblePos: mapDir(d.getPositionYangGui ? d.getPositionYangGui() : (d.getDayPositionYangGui ? d.getDayPositionYangGui() : '查无')),
          chong: d.getDayChongDesc ? d.getDayChongDesc() : '无',
          sha: d.getDaySha ? d.getDaySha() : '无',
          pengZuGan: d.getPengZuGan ? d.getPengZuGan() : '无',
          pengZuZhi: d.getPengZuZhi ? d.getPengZuZhi() : '无',
          hours: hoursList
        };

        if (mounted) {
          setLunarData(data);
          setErrorMsg(null);
        }

      } catch (e: any) {
        console.error("Lunar Load Error:", e);
        if (mounted) setErrorMsg(e.message || String(e));
      }
    };

    loadData();

    return () => { mounted = false; };
  }, [now]);

  if (!chart) return <div className="p-8 text-center text-slate-400">请先排盘以查看运势。</div>;

  const selectedDaYun = chart?.daYun ? chart.daYun[selectedDaYunIndex] : null;

  return (
    <div className="space-y-6 animate-in fade-in duration-500">

      {/* Navigation */}
      <div className="flex p-1 bg-slate-100 rounded-xl w-full sm:w-fit mx-auto sm:mx-0 sticky top-0 z-10 shadow-sm">
        <button
          onClick={() => setViewMode('fortune')}
          className={`flex-1 sm:flex-none px-6 py-2 rounded-lg text-sm font-bold transition-all flex items-center justify-center gap-2 ${viewMode === 'fortune' ? 'bg-white text-violet-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
        >
          <Sun size={16} /> 今日必读
        </button>
        <button
          onClick={() => setViewMode('dayun')}
          className={`flex-1 sm:flex-none px-6 py-2 rounded-lg text-sm font-bold transition-all flex items-center justify-center gap-2 ${viewMode === 'dayun' ? 'bg-white text-violet-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
        >
          <TrendingUp size={16} /> 一生大运
        </button>
      </div>

      {/* --- View 1: Fortune Dashboard --- */}
      {viewMode === 'fortune' && (
        <div className="space-y-6">

          {!lunarData ? (
            <div className="p-8 bg-amber-50 text-amber-900 rounded-xl border border-amber-100 text-center">
              {errorMsg ? (
                <>
                  <AlertCircle className="mx-auto mb-2 text-rose-500" />
                  <p className="font-bold text-rose-600">万年历加载失败</p>
                  <div className="mt-2 text-xs font-mono bg-white p-2 text-left rounded border border-rose-100 overflow-auto max-h-32 text-rose-800 break-all">
                    DEBUG: {errorMsg}
                  </div>
                </>
              ) : (
                <>
                  <ArrowRight className="mx-auto mb-2 animate-spin text-amber-500" />
                  <p>正在计算星历数据...</p>
                </>
              )}
            </div>
          ) : (
            <>
              {/* Hero Cards */}
              <div className="bg-gradient-to-br from-violet-600 to-indigo-800 rounded-2xl p-6 text-white shadow-lg relative overflow-hidden">
                <div className="absolute top-0 right-0 w-40 h-40 bg-white opacity-5 rounded-full blur-3xl -mr-10 -mt-10"></div>
                <div className="relative z-10">
                  <div className="flex justify-between items-start mb-6">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <span className="bg-white/20 px-2 py-0.5 rounded text-[10px] font-bold backdrop-blur-sm">{lunarData.ganZhiYear}年</span>
                        <span className="bg-white/20 px-2 py-0.5 rounded text-[10px] font-bold backdrop-blur-sm">{lunarData.ganZhiMonth}月</span>
                        {lunarData.zhiXing && <span className="bg-amber-400/80 text-amber-900 px-2 py-0.5 rounded text-[10px] font-bold">{lunarData.zhiXing}日</span>}
                        {lunarData.naYin && <span className="bg-emerald-400/80 text-emerald-900 px-2 py-0.5 rounded text-[10px] font-bold flex items-center gap-1">{lunarData.naYin}</span>}
                      </div>
                      <div className="text-4xl font-serif font-bold mb-1">{lunarData.cnMonth}月{lunarData.cnDay}</div>
                      <div className="text-violet-200 text-xs opacity-80">{now.toLocaleDateString()} {['周日', '周一', '周二', '周三', '周四', '周五', '周六'][now.getDay()]}</div>
                    </div>
                    <div className="text-center">
                      <div className="text-4xl font-serif font-black text-transparent bg-clip-text bg-gradient-to-b from-white to-violet-200">{lunarData.ganZhiDay}</div>
                      <div className="text-[10px] text-violet-300 uppercase tracking-widest mt-1">当日干支</div>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4 bg-white/5 rounded-xl p-1 backdrop-blur-sm border border-white/10">
                    <div className="p-3 text-center border-r border-white/10">
                      <div className="text-emerald-300 font-bold text-xs mb-1 flex items-center justify-center gap-1"><div className="w-1.5 h-1.5 rounded-full bg-emerald-400"></div> 宜 (Do)</div>
                      <p className="text-xs text-white/90 leading-relaxed line-clamp-2">{lunarData.yi.join(' ')}</p>
                    </div>
                    <div className="p-3 text-center">
                      <div className="text-rose-300 font-bold text-xs mb-1 flex items-center justify-center gap-1"><div className="w-1.5 h-1.5 rounded-full bg-rose-400"></div> 忌 (Don't)</div>
                      <p className="text-xs text-white/90 leading-relaxed line-clamp-2">{lunarData.ji.join(' ')}</p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
                <h3 className="font-bold text-slate-700 text-sm mb-4 flex items-center gap-2"><Compass className="text-blue-500" size={16} /> 吉神方位 (Lucky Directions)</h3>
                <div className="grid grid-cols-3 gap-2">
                  <div className="bg-slate-50 rounded-lg p-3 text-center border border-slate-100"><div className="text-[10px] text-slate-400 mb-1">财神 (Wealth)</div><div className="font-bold text-slate-700">{lunarData.wealthPos}</div></div>
                  <div className="bg-slate-50 rounded-lg p-3 text-center border border-slate-100"><div className="text-[10px] text-slate-400 mb-1">喜神 (Joy)</div><div className="font-bold text-slate-700">{lunarData.joyPos}</div></div>
                  <div className="bg-slate-50 rounded-lg p-3 text-center border border-slate-100"><div className="text-[10px] text-slate-400 mb-1">贵人 (Noble)</div><div className="font-bold text-slate-700">{lunarData.noblePos}</div></div>
                </div>
              </div>

              <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
                <h3 className="font-bold text-slate-700 text-sm mb-4 flex items-center gap-2"><Clock className="text-amber-500" size={16} /> 十二时辰吉凶</h3>
                <div className="flex overflow-x-auto gap-3 pb-2 scrollbar-hide snap-x">
                  {lunarData.hours.map((h: any, idx: number) => {
                    const isLucky = h.luck === '吉';
                    return (
                      <div key={h.zhi} className={`snap-center flex-shrink-0 w-20 bg-slate-50 rounded-lg p-2 text-center border ${isLucky ? 'border-emerald-100 bg-emerald-50/50' : 'border-slate-100'} flex flex-col items-center group relative`}>
                        <div className="text-xs font-bold text-slate-700 mb-1">{h.zhi}时</div>
                        <div className="text-[10px] text-slate-400 mb-1 scale-90">{h.time}</div>
                        <div className={`w-full py-0.5 text-[10px] rounded font-bold ${isLucky ? 'bg-emerald-100 text-emerald-700' : 'bg-rose-100 text-rose-700'}`}>{h.god} {h.luck}</div>
                      </div>
                    )
                  })}
                </div>
              </div>

              {/* Gods Lists */}
              <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
                <div className="grid grid-cols-2 gap-6">
                  <div>
                    <h4 className="font-bold text-emerald-600 text-xs mb-2 flex items-center gap-1"><Sparkles size={12} /> 吉神 (Lucky Gods)</h4>
                    <div className="flex flex-wrap gap-1.5">
                      {lunarData.jiShen?.length > 0 ? lunarData.jiShen.slice(0, 8).map((g: string) => <span key={g} className="text-[10px] bg-emerald-50 text-emerald-700 px-1.5 py-0.5 rounded border border-emerald-100">{g}</span>) : <span className="text-[10px] text-slate-400">无</span>}
                    </div>
                  </div>
                  <div>
                    <h4 className="font-bold text-rose-600 text-xs mb-2 flex items-center gap-1"><AlertTriangle size={12} /> 凶神 (Fierce Gods)</h4>
                    <div className="flex flex-wrap gap-1.5">
                      {lunarData.xiongSha?.length > 0 ? lunarData.xiongSha.slice(0, 8).map((g: string) => <span key={g} className="text-[10px] bg-rose-50 text-rose-700 px-1.5 py-0.5 rounded border border-rose-100">{g}</span>) : <span className="text-[10px] text-slate-400">无</span>}
                    </div>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
                  <h3 className="font-bold text-slate-700 text-sm mb-3 flex items-center gap-2"><AlertTriangle className="text-rose-500" size={16} /> 今日冲煞</h3>
                  <div className="space-y-3">
                    <div className="flex justify-between items-center text-sm"><span className="text-slate-500">日破 (Clash)</span><span className="font-medium text-slate-800">{lunarData.chong}</span></div>
                    <div className="w-full h-px bg-slate-50"></div>
                    <div className="flex justify-between items-center text-sm"><span className="text-slate-500">煞方 (Bad Dir)</span><span className="font-medium text-slate-800">{lunarData.sha}</span></div>
                  </div>
                </div>
                <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100">
                  <h3 className="font-bold text-slate-700 text-sm mb-3 flex items-center gap-2"><FileText className="text-indigo-500" size={16} /> 彭祖百忌</h3>
                  <div className="space-y-2">
                    <div className="text-xs text-slate-600 bg-slate-50 p-2 rounded"><strong className="text-indigo-600 mr-1">{lunarData.ganZhiDay[0]}:</strong>{lunarData.pengZuGan}</div>
                    <div className="text-xs text-slate-600 bg-slate-50 p-2 rounded"><strong className="text-indigo-600 mr-1">{lunarData.ganZhiDay[1]}:</strong>{lunarData.pengZuZhi}</div>
                  </div>
                </div>
              </div>
            </>
          )}

          {/* AI Guide - Inline & Persistent */}
          {!aiGuide ? (
            <button
              onClick={handleGenerateGuide}
              disabled={isGenerating}
              className="w-full text-left bg-gradient-to-r from-violet-100 to-fuchsia-100 border border-violet-200 rounded-2xl p-4 flex justify-between items-center cursor-pointer hover:shadow-md transition-all group disabled:opacity-70 disabled:cursor-wait"
            >
              <div>
                <h4 className="font-bold text-violet-900 text-sm mb-0.5 flex items-center gap-2">
                  {isGenerating ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} className="text-violet-600" />}
                  想知道今日财运与事业机遇？
                </h4>
                <p className="text-xs text-violet-700">结合您八字的精准 AI 每日指南 (每日限一次)</p>
              </div>
              <div className="w-8 h-8 rounded-full bg-white text-violet-600 flex items-center justify-center shadow-sm group-hover:scale-110 transition-transform">
                <ArrowRight size={16} />
              </div>
            </button>
          ) : (
            <div className="bg-white rounded-2xl shadow-sm border border-violet-100 overflow-hidden animate-in fade-in slide-in-from-bottom-2">
              <div className="bg-violet-50/50 p-4 border-b border-violet-100 flex justify-between items-center">
                <h4 className="font-bold text-violet-900 text-sm flex items-center gap-2">
                  <Sparkles size={16} className="text-violet-600" />
                  天机·每日流年指南
                </h4>
                <span className="text-[10px] text-violet-400 bg-white px-2 py-0.5 rounded border border-violet-100">
                  {now.getFullYear()}-{now.getMonth() + 1}-{now.getDate()}
                </span>
              </div>
              <div className="p-5">
                {/* Call safe internal markdown renderer */}
                <SimpleMarkdown content={aiGuide} />
              </div>
              <div className="bg-slate-50 p-2 text-center">
                <p className="text-[10px] text-slate-400">AI 生成内容仅供参考 · 明日可再次生成</p>
              </div>
            </div>
          )}
        </div>
      )}

      {/* --- View 2: Da Yun (Existing) --- */}
      {viewMode === 'dayun' && (
        <div className="space-y-6 animate-in slide-in-from-right-4 duration-300">
          {/* Fixed DaYun Layout */}
          <div className="relative">
            <div className="flex overflow-x-auto gap-3 pb-4 pt-1 px-1 scrollbar-hide snap-x mask-linear-fade">
              {chart?.daYun.map((yun, idx) => {
                const isSelected = selectedDaYunIndex === idx;
                return (
                  <button
                    key={idx}
                    onClick={() => { setSelectedDaYunIndex(idx); setSelectedYear(null); }}
                    className={`
                                  group relative flex flex-col items-center justify-between
                                  min-w-[70px] h-[100px] p-2 rounded-2xl border transition-all duration-300 snap-center
                                  ${isSelected
                        ? 'bg-violet-600 border-violet-600 shadow-lg shadow-violet-200 -translate-y-1'
                        : 'bg-white border-slate-100 hover:border-violet-200 hover:bg-slate-50'}
                              `}
                  >
                    <span className={`text-[10px] font-medium ${isSelected ? 'text-violet-200' : 'text-slate-400'}`}>
                      {yun.startAge}岁
                    </span>

                    <div className={`flex flex-col items-center my-1 ${isSelected ? 'text-white' : 'text-slate-700'}`}>
                      <span className={`text-[9px] mb-0.5 ${isSelected ? 'text-violet-200' : 'text-slate-400'}`}>{yun.ganGod}</span>
                      <div className="text-xl font-serif font-black leading-none flex flex-col items-center">
                        <span>{yun.gan}</span>
                        <span className="mt-0.5">{yun.zhi}</span>
                      </div>
                    </div>

                    <span className={`text-[10px] ${isSelected ? 'text-violet-200' : 'text-slate-400'}`}>
                      {yun.startYear}
                    </span>

                    {isSelected && (
                      <div className="absolute -bottom-2 w-1.5 h-1.5 rounded-full bg-violet-600" />
                    )}
                  </button>
                );
              })}
            </div>
          </div>

          {selectedDaYun && (
            <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden animate-in fade-in slide-in-from-bottom-2 duration-300">
              <div className="px-5 py-4 border-b border-slate-50 bg-slate-50/50 flex justify-between items-center">
                <div>
                  <h4 className="font-bold text-slate-800 text-lg flex items-center gap-2">
                    <span className="font-serif bg-violet-100 text-violet-700 px-2 py-0.5 rounded text-base">
                      {selectedDaYun.gan}{selectedDaYun.zhi}
                    </span>
                    <span>大运详情</span>
                  </h4>
                </div>
                <div className="text-xs text-slate-400 font-mono bg-white px-2 py-1 rounded border border-slate-100">
                  {selectedDaYun.startYear} - {selectedDaYun.startYear + 9}
                </div>
              </div>

              <div className="p-4 bg-slate-50/30">
                <h5 className="text-xs font-bold text-slate-400 uppercase mb-3 flex items-center gap-1">流年运势</h5>
                <div className="grid grid-cols-2 min-[450px]:grid-cols-3 sm:grid-cols-5 gap-3">
                  {selectedDaYun.liuNian.map((year, idx) => {
                    const isActive = selectedYear?.year === year.year;
                    return (
                      <button key={idx} onClick={() => setSelectedYear(year)} className={`relative rounded-xl p-3 border transition-all duration-200 group cursor-pointer text-left ${isActive ? 'bg-white border-violet-500 ring-2 ring-violet-200 shadow-md transform -translate-y-0.5' : 'bg-white border-slate-100 hover:border-violet-300 hover:shadow-sm'}`}>
                        <div className="flex justify-between items-start mb-2">
                          <span className="text-[10px] font-mono text-slate-400">{year.year}</span>
                          <span className={`text-[10px] font-medium px-1.5 rounded-full ${isActive ? 'bg-violet-100 text-violet-600' : 'bg-slate-100 text-slate-500'}`}>{year.age}岁</span>
                        </div>
                        <div className="text-center mb-2 flex flex-col items-center">
                          <span className={`text-[10px] mb-0.5 font-bold scale-90 ${isActive ? 'text-violet-600' : 'text-slate-400'}`}>{year.ganGod}</span>
                          <span className={`text-lg font-serif font-black leading-none ${isActive ? 'text-violet-900' : 'text-slate-800'}`}>{year.gan}{year.zhi}</span>
                        </div>
                      </button>
                    )
                  })}
                </div>

                {selectedYear && (
                  <div className="mt-4 p-4 rounded-xl bg-white border border-violet-100 shadow-sm animate-in fade-in slide-in-from-top-2 relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-1 h-full bg-violet-500"></div>
                    <div className="flex items-center gap-2 mb-3">
                      <span className="text-2xl font-serif font-black text-slate-800">{selectedYear.gan}{selectedYear.zhi}</span>
                      <span className="text-sm text-slate-400 font-mono pt-1">{selectedYear.year}年</span>
                      <span className="ml-auto px-2 py-1 rounded bg-violet-50 text-violet-700 text-xs font-bold border border-violet-100">{selectedYear.ganGod}年</span>
                    </div>
                    <div className="bg-slate-50 p-3 rounded-lg text-xs sm:text-sm">
                      <div className="text-slate-600 leading-relaxed">{TEN_GOD_INFO[selectedYear.ganGod]}</div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// tianji-mp/src/components/Timeline.vue
<template>
  <view class="timeline-container animate-fade-in">

    <!-- Navigation -->
    <view class="nav-bar">
      <view 
        class="nav-btn" 
        :class="{ active: viewMode === 'fortune' }"
        @click="viewMode = 'fortune'"
      >
        <text class="nav-icon">☀</text>
        <text>今日必读</text>
      </view>
       <view 
        class="nav-btn" 
        :class="{ active: viewMode === 'dayun' }"
        @click="viewMode = 'dayun'"
      >
        <text class="nav-icon">📈</text>
        <text>一生大运</text>
      </view>
    </view>

    <!-- View 1: Fortune -->
    <view v-if="viewMode === 'fortune'" class="fortune-view">
        <view v-if="!lunarData" class="loading-box">
             <view v-if="errorMsg" class="error-msg">
                 <text>⚠ 万年历加载失败: {{ errorMsg }}</text>
             </view>
             <view v-else class="loading-text">
                 <text>↻ 正在计算星历数据...</text>
             </view>
        </view>
        
        <block v-else>
            <!-- Hero Card -->
            <view class="hero-card">
                 <view class="hero-top">
                     <view class="hero-info">
                         <view class="tags-row">
                             <text class="tag-glass">{{ lunarData.ganZhiYear }}年</text>
                             <text class="tag-glass">{{ lunarData.ganZhiMonth }}月</text>
                             <text v-if="lunarData.zhiXing" class="tag-amber">{{ lunarData.zhiXing }}日</text>
                         </view>
                         <view class="date-big">{{ lunarData.cnMonth }}月{{ lunarData.cnDay }}</view>
                         <view class="date-sub">{{ nowDateStr }} {{ weekDayStr }}</view>
                     </view>
                     <view class="hero-ganzhi">
                         <text class="ganzhi-main">{{ lunarData.ganZhiDay }}</text>
                         <text class="ganzhi-sub">当日干支</text>
                     </view>
                 </view>
                 
                 <view class="yiji-box">
                     <view class="yiji-col border-r">
                         <view class="yiji-title green"><text class="dot green-dot"></text> 宜 (Do)</view>
                         <text class="yiji-content">{{ lunarData.yi.join(' ') }}</text>
                     </view>
                     <view class="yiji-col">
                         <view class="yiji-title red"><text class="dot red-dot"></text> 忌 (Don't)</view>
                         <text class="yiji-content">{{ lunarData.ji.join(' ') }}</text>
                     </view>
                 </view>
            </view>
            
            <!-- Lucky Directions -->
            <view class="card">
                <view class="card-header"><text class="icon">🧭</text> <text>吉神方位</text></view>
                <view class="dir-grid">
                    <view class="dir-item">
                        <text class="dir-label">财神</text>
                        <text class="dir-val">{{ lunarData.wealthPos }}</text>
                    </view>
                     <view class="dir-item">
                        <text class="dir-label">喜神</text>
                        <text class="dir-val">{{ lunarData.joyPos }}</text>
                    </view>
                     <view class="dir-item">
                        <text class="dir-label">贵人</text>
                        <text class="dir-val">{{ lunarData.noblePos }}</text>
                    </view>
                </view>
            </view>
            
            <!-- 12 Hours -->
            <view class="card">
                <view class="card-header"><text class="icon">🕒</text> <text>十二时辰吉凶</text></view>
                <scroll-view scroll-x class="hours-scroll">
                    <view class="hours-flex">
                        <view v-for="(h, idx) in lunarData.hours" :key="idx" 
                              class="hour-item" :class="{ 'lucky-hour': h.luck === '吉' }">
                            <text class="hour-zhi">{{ h.zhi }}时</text>
                            <text class="hour-time">{{ h.time }}</text>
                            <text class="hour-tag" :class="h.luck === '吉' ? 'tag-green' : 'tag-red'">
                                {{ h.god }} {{ h.luck }}
                            </text>
                        </view>
                    </view>
                </scroll-view>
            </view>
            
            <!-- Gods List -->
            <view class="card">
                <view class="gods-grid">
                    <view class="gods-col">
                         <view class="gods-head green-txt">✨ 吉神</view>
                         <view class="gods-tags">
                             <text v-for="g in (lunarData.jiShen || []).slice(0,8)" :key="g" class="god-tag green-bg">{{ g }}</text>
                         </view>
                    </view>
                     <view class="gods-col">
                         <view class="gods-head red-txt">⚠ 凶神</view>
                         <view class="gods-tags">
                             <text v-for="g in (lunarData.xiongSha || []).slice(0,8)" :key="g" class="god-tag red-bg">{{ g }}</text>
                         </view>
                    </view>
                </view>
            </view>
            
            <!-- Chong Sha & Peng Zu -->
            <view class="grid-2">
                <view class="card">
                    <view class="card-header-sm">⚠ 今日冲煞</view>
                    <view class="row-between"><text class="gray">日破</text><text class="bold">{{ lunarData.chong }}</text></view>
                    <view class="divider"></view>
                    <view class="row-between"><text class="gray">煞方</text><text class="bold">{{ lunarData.sha }}</text></view>
                </view>
                 <view class="card">
                    <view class="card-header-sm">📜 彭祖百忌</view>
                    <view class="peng-item"><text class="indigo">{{ lunarData.ganZhiDay[0] }}:</text> {{ lunarData.pengZuGan }}</view>
                    <view class="peng-item"><text class="indigo">{{ lunarData.ganZhiDay[1] }}:</text> {{ lunarData.pengZuZhi }}</view>
                </view>
            </view>
            
            <!-- AI Guide -->
            <view class="card ai-card">
                <view class="ai-header">
                    <view class="ai-head-left">
                        <text class="icon">✨</text>
                        <text class="ai-title">AI 每日指南</text>
                    </view>
                </view>
                <view v-if="isGenerating" class="ai-loading">
                    <view class="spinner-sm"></view>
                    <text class="gray">正在请求天机先生...</text>
                </view>
                <view v-else-if="aiGuide" class="ai-content">
                    <view v-for="(item, idx) in aiGuideItems" :key="idx" class="ai-item">
                        <text class="ai-label">{{ item.label }}</text>
                        <text class="ai-text" space="nbsp">{{ item.text }}</text>
                    </view>
                </view>
                <view v-else class="ai-empty">
                    <text class="gray-desc">结合今日黄历、八字命盘，生成个性化操作指引。</text>
                    <button class="btn-secondary" @click="handleGenerateGuide">生成今日指引</button>
                </view>
            </view>
            
        </block>
    </view>

    <!-- View 2: Da Yun -->
    <view v-if="viewMode === 'dayun'" class="dayun-view">
        <scroll-view scroll-x class="dayun-scroll">
            <view class="dayun-flex">
                <view 
                    v-for="(yun, idx) in chart?.daYun" 
                    :key="idx"
                    class="dayun-item"
                    :class="{ active: selectedDaYunIndex === idx }"
                    @click="handleDayunSelect(idx)"
                >
                    <text class="dy-age">{{ yun.startAge }}岁</text>
                    <view class="dy-ganzhi">
                        <text class="dy-god">{{ yun.ganGod }}</text>
                        <text class="dy-char">{{ yun.gan }}</text>
                        <text class="dy-char">{{ yun.zhi }}</text>
                    </view>
                    <text class="dy-year">{{ yun.startYear }}</text>
                </view>
            </view>
        </scroll-view>
        
        <!-- Details -->
        <view v-if="selectedDaYun" class="card detail-card">
            <view class="detail-header">
                <view class="dh-left">
                    <text class="dh-title">{{ selectedDaYun.gan }}{{ selectedDaYun.zhi }}大运</text>
                    <text class="dh-sub">大运详情</text>
                </view>
                <text class="dh-range">{{ selectedDaYun.startYear }} - {{ selectedDaYun.startYear + 9 }}</text>
            </view>
            
            <view class="liunian-grid">
                <view 
                    v-for="(year, idx) in selectedDaYun.liuNian" 
                    :key="idx" 
                    class="ln-item"
                    :class="{ active: selectedYear?.year === year.year }"
                    @click="selectedYear = year"
                >
                     <view class="ln-top">
                         <text class="mono">{{ year.year }}</text>
                         <text class="age-badge">{{ year.age }}岁</text>
                     </view>
                     <view class="ln-mid">
                         <text class="ln-god">{{ year.ganGod }}</text>
                         <text class="ln-gz">{{ year.gan }}{{ year.zhi }}</text>
                     </view>
                </view>
            </view>
            
            <view v-if="selectedYear" class="info-year-box animate-fade-in">
                 <view class="iy-header">
                     <text class="iy-gz">{{ selectedYear.gan }}{{ selectedYear.zhi }}</text>
                     <text class="iy-year">{{ selectedYear.year }}年</text>
                     <text class="iy-god-tag">{{ selectedYear.ganGod }}年</text>
                 </view>
                 <view class="iy-desc">
                     {{ TEN_GOD_INFO[selectedYear.ganGod] }}
                 </view>
            </view>
        </view>
    </view>
    
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import type { BaziChart, DaYunData, LiuNianData } from '@/models';
import { Lunar } from 'lunar-javascript';
import { generateDailyGuide, DailyFortuneAPI } from '@/services/aiService';

const props = defineProps<{
  chart: BaziChart | undefined | null
}>();

const viewMode = ref<'fortune' | 'dayun'>('fortune');
const selectedDaYunIndex = ref(0);
const selectedYear = ref<LiuNianData | null>(null);
const now = ref(new Date());

const lunarData = ref<any>(null);
const errorMsg = ref<string | null>(null);
const aiGuide = ref<string | null>(null);
const isGenerating = ref(false);

const TEN_GOD_INFO: Record<string, string> = {
  '比肩': '兄弟朋友助力，利合作盟友。但亦有竞争夺财之象，忌独断专行。',
  '劫财': '个性刚强，易冲动破财。虽然人脉广，但不利积蓄，需防小人争斗。',
  '食神': '福气临门，衣食无忧，心情舒畅。利于才艺创作与享受生活，诸事平顺。',
  '伤官': '思维活跃，才华横溢。但易变动工作或招惹口舌是非，利创新，忌傲慢。',
  '正财': '财运稳定，多为工薪正途之财。利积蓄守成，男命此时利于姻缘建立。',
  '偏财': '意外之财，投资获利机会多。财路宽广但也易大起大落，忌贪婪冒进。',
  '正官': '事业升迁，名誉地位提升。利于考试、求职与升职，女命利夫运。',
  '七杀': '压力增大，挑战与机遇并存。虽有魄力开拓但易生意外或疾病，宜守忌攻。',
  '正印': '贵人提拔，利名声学业。生活安逸稳定，少劳苦，多得长辈庇护。',
  '偏印': '思想独特，灵感丰富。利于冷门偏业或学术研究，但性格多孤僻，防孤独。'
};

const TIMING_MAP = ['23-01', '01-03', '03-05', '05-07', '07-09', '09-11', '11-13', '13-15', '15-17', '17-19', '19-21', '21-23'];
const SHI_CHEN = ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥'];
const DIRECTION_MAP: Record<string, string> = {
  '坎': '正北', '离': '正南', '震': '正东', '兑': '正西',
  '巽': '东南', '坤': '西南', '艮': '东北', '乾': '西北',
  '中': '中宫'
};

type AiGuideItem = {
    label: string;
    text: string;
};

type AiGuideKey = 'quote' | 'wealth' | 'career' | 'love' | 'caution' | 'lucky' | 'other';

const buildZhLabel = (...codes: number[]) => String.fromCharCode(...codes);
const AI_GUIDE_LABELS: { key: AiGuideKey; label: string }[] = [
    { key: 'quote', label: buildZhLabel(0x4eca, 0x65e5, 0x4e00, 0x8a00) },
    { key: 'wealth', label: buildZhLabel(0x8d22, 0x8fd0, 0x65b9, 0x4f4d) },
    { key: 'career', label: buildZhLabel(0x4e8b, 0x4e1a, 0x673a, 0x7f18) },
    { key: 'love', label: buildZhLabel(0x60c5, 0x611f, 0x4eba, 0x9645) },
    { key: 'caution', label: buildZhLabel(0x907f, 0x9669, 0x6307, 0x5357) },
    { key: 'lucky', label: buildZhLabel(0x5929, 0x673a, 0x9526, 0x56ca) }
];

const normalizeAiKey = (raw: string): AiGuideKey => {
    const cleaned = raw
        .replace(/\*\*/g, '')
        .replace(/[\uFF1A:]+$/, '')
        .replace(/^[\u3010\uFF08\[\(]+|[\u3011\uFF09\]\)]+$/g, '')
        .replace(/[^a-zA-Z0-9\u4e00-\u9fa5]+/g, '')
        .toLowerCase();
    if (!cleaned) return 'other';
    if (cleaned.includes('quote') || cleaned.includes('\u4eca\u65e5')) return 'quote';
    if (cleaned.includes('wealth') || cleaned.includes('\u8d22')) return 'wealth';
    if (cleaned.includes('career') || cleaned.includes('\u4e8b\u4e1a')) return 'career';
    if (cleaned.includes('love') || cleaned.includes('\u60c5') || cleaned.includes('\u611f\u60c5')) return 'love';
    if (cleaned.includes('caution') || cleaned.includes('\u907f') || cleaned.includes('\u6ce8\u610f')) return 'caution';
    if (cleaned.includes('lucky') || cleaned.includes('\u5e78\u8fd0') || cleaned.includes('\u989c\u8272') || cleaned.includes('\u9526\u56ca')) return 'lucky';
    return 'other';
};
const nowDateStr = computed(() => now.value.toLocaleDateString());
const weekDayStr = computed(() => ['周日', '周一', '周二', '周三', '周四', '周五', '周六'][now.value.getDay()]);
const aiGuideItems = computed<AiGuideItem[]>(() => {
    if (!aiGuide.value) return [];
    const parsed: Partial<Record<AiGuideKey, string>> = {};
    const extras: string[] = [];
    let currentKey: AiGuideKey | null = null;
    const appendValue = (key: AiGuideKey, text: string) => {
        if (!text) return;
        if (parsed[key]) {
            parsed[key] = `${parsed[key]}\n${text}`;
        } else {
            parsed[key] = text;
        }
    };
    aiGuide.value
        .split(/\r?\n/)
        .map(line => line.trim())
        .filter(Boolean)
        .map(line => line.replace(/^>+\s*/, '').replace(/^#+\s*/, '').replace(/^[\-\*\u2022\d\.\)\s]+/, '').replace(/\*\*/g, '').trim())
        .forEach((line) => {
            if (!line) return;
            const labelMatch = line.match(/^(.{1,12}?)[\uFF1A:]\s*(.+)$/);
            if (labelMatch) {
                const label = labelMatch[1].trim();
                const text = labelMatch[2].trim();
                if (!text) return;
                const key = normalizeAiKey(label);
                if (key === 'other') {
                    extras.push(text);
                    currentKey = null;
                    return;
                }
                currentKey = key;
                appendValue(key, text);
                return;
            }

            if (currentKey) {
                appendValue(currentKey, line);
                return;
            }

            extras.push(line);
        });

    if (extras.length) {
        const extraText = extras.join('\n');
        if (parsed.lucky) {
            parsed.lucky = `${parsed.lucky}\n${extraText}`;
        } else {
            parsed.lucky = extraText;
        }
    }

    const items: AiGuideItem[] = [];
    AI_GUIDE_LABELS.forEach((item) => {
        const value = parsed[item.key];
        if (value) {
            items.push({ label: item.label, text: value });
        }
    });
    return items;
});

const sessionIdentity = computed(() => {
    if (!props.chart) return null;
    const todayStr = `${now.value.getFullYear()}-${now.value.getMonth() + 1}-${now.value.getDate()}`;
    const safeId = (props.chart.meta.solarDate + props.chart.meta.gender).replace(/[^a-zA-Z0-9]/g, '');
    return { id: safeId, date: todayStr };
});

const loadDailyGuide = async () => {
    if (!sessionIdentity.value) return;
    const cached = await DailyFortuneAPI.get(sessionIdentity.value.id, sessionIdentity.value.date);
    if (cached) {
        aiGuide.value = cached;
    }
};

const loadLunar = async () => {
    try {
        const d = Lunar.fromDate(now.value);
        if (!d) return;

        const hoursList = [];
        const startOfDay = new Date(now.value);
        startOfDay.setHours(0, 0, 0, 0);

        for (let i = 0; i < 12; i++) {
            const h = i * 2;
            const tmpDate = new Date(startOfDay);
            tmpDate.setHours(h);
            const tmpLunar = Lunar.fromDate(tmpDate);

            const god = tmpLunar.getTimeTianShen ? tmpLunar.getTimeTianShen() : '';
            const luck = tmpLunar.getTimeTianShenLuck ? tmpLunar.getTimeTianShenLuck() : '';

            hoursList.push({
                zhi: SHI_CHEN[i],
                time: TIMING_MAP[i],
                god,
                luck
            });
        }

        const mapDir = (val: string) => DIRECTION_MAP[val] || val;

        const data = {
            ganZhiYear: d.getYearInGanZhi(),
            ganZhiMonth: d.getMonthInGanZhi(),
            ganZhiDay: d.getDayInGanZhi(),
            cnMonth: d.getMonthInChinese(),
            cnDay: d.getDayInChinese(),
            yi: d.getDayYi(),
            ji: d.getDayJi(),
            zhiXing: d.getZhiXing(),
            jiShen: d.getDayJiShen(),
            xiongSha: d.getDayXiongSha(),
            wealthPos: mapDir(d.getPositionCai()),
            joyPos: mapDir(d.getPositionXi()),
            noblePos: mapDir(d.getPositionYangGui()),
            chong: d.getDayChongDesc(),
            sha: d.getDaySha(),
            pengZuGan: d.getPengZuGan(),
            pengZuZhi: d.getPengZuZhi(),
            hours: hoursList
        };
        lunarData.value = data;
        await loadDailyGuide();
    } catch (e: any) {
        console.error('Lunar error', e);
        errorMsg.value = e.message;
    }
};

onMounted(() => {
    loadLunar();
    if (props.chart?.daYun) {
        const currentYear = new Date().getFullYear();
        const idx = props.chart.daYun.findIndex(dy => currentYear >= dy.startYear && currentYear <= (dy.startYear + 9));
        if(idx >= 0) {
            selectedDaYunIndex.value = idx;
            const yn = props.chart.daYun[idx].liuNian.find(y => y.year === currentYear);
            if(yn) selectedYear.value = yn;
        }
    }
});

const selectedDaYun = computed(() => {
    return props.chart?.daYun ? props.chart.daYun[selectedDaYunIndex.value] : null;
});

const handleDayunSelect = (idx: number) => {
    selectedDaYunIndex.value = idx;
    selectedYear.value = null;
};

const handleGenerateGuide = async () => {
    if (!props.chart || !lunarData.value || !sessionIdentity.value || isGenerating.value) return;
    isGenerating.value = true;
    try {
        const result = await generateDailyGuide(props.chart, {
            ganZhiYear: lunarData.value.ganZhiYear,
            ganZhiMonth: lunarData.value.ganZhiMonth,
            ganZhiDay: lunarData.value.ganZhiDay,
            cnMonth: lunarData.value.cnMonth,
            cnDay: lunarData.value.cnDay,
            jiShen: lunarData.value.jiShen,
            naYin: lunarData.value.naYin,
            chong: lunarData.value.chong
        });
        aiGuide.value = result;
        await DailyFortuneAPI.save(sessionIdentity.value.id, sessionIdentity.value.date, result);
    } catch (e: any) {
        uni.showToast({ title: 'AI指引失败: ' + (e.message || '请检查配置'), icon: 'none' });
    } finally {
        isGenerating.value = false;
    }
};

</script>

<style scoped>
.timeline-container {
    display: flex;
    flex-direction: column;
    gap: 24rpx;
    width: 100%;
    box-sizing: border-box;
}
.animate-fade-in { animation: fadeIn 0.5s; opacity: 1; }
@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }

/* Nav */
.nav-bar {
    display: flex;
    background: #f1f5f9;
    padding: 8rpx;
    border-radius: 16rpx;
}
.nav-btn {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 12rpx;
    padding: 16rpx;
    font-size: 28rpx;
    color: #64748b;
    border-radius: 12rpx;
}
.nav-btn.active {
    background: #fff;
    color: #7c3aed;
    font-weight: bold;
    box-shadow: 0 2rpx 4rpx rgba(0,0,0,0.05);
}

/* Fortune View */
.loading-box {
    padding: 32rpx;
    background: #fffbeb;
    border-radius: 16rpx;
    text-align: center;
    color: #b45309;
}
.hero-card {
    background: linear-gradient(135deg, #7c3aed, #4338ca);
    border-radius: 24rpx;
    padding: 24rpx;
    color: #fff;
    margin-bottom: 24rpx;
    width: 100%;
    box-sizing: border-box;
}
.hero-top {
    display: flex;
    justify-content: space-between;
    margin-bottom: 24rpx;
}
.tags-row { display: flex; gap: 8rpx; margin-bottom: 8rpx; }
.tag-glass { background: rgba(255,255,255,0.2); padding: 4rpx 12rpx; border-radius: 8rpx; font-size: 20rpx; }
.tag-amber { background: rgba(251, 191, 36, 0.9); color: #78350f; padding: 4rpx 12rpx; border-radius: 8rpx; font-size: 20rpx; font-weight: bold; }
.date-big { font-size: 48rpx; font-weight: bold; font-family: serif; }
.date-sub { font-size: 24rpx; opacity: 0.8; }
.ganzhi-main { font-size: 64rpx; font-weight: 900; font-family: serif; display: block; line-height: 1; margin-bottom: 8rpx; text-transparent: transparent; background-clip: text; -webkit-background-clip: text; background-image: linear-gradient(to bottom, #fff, #ddd6fe); color: white; }
.ganzhi-sub { font-size: 20rpx; opacity: 0.8; letter-spacing: 2rpx; text-transform: uppercase; text-align: center; font-weight: bold; color: #ddd6fe; display: block; }

.yiji-box {
    background: rgba(255,255,255,0.1);
    backdrop-filter: blur(10px);
    border-radius: 16rpx;
    display: flex;
    border: 1px solid rgba(255,255,255,0.1);
}
.yiji-col { flex: 1; padding: 16rpx; }
.border-r { border-right: 1px solid rgba(255,255,255,0.1); }
.yiji-title { font-size: 24rpx; font-weight: bold; margin-bottom: 8rpx; display: flex; align-items: center; gap: 8rpx; }
.green { color: #6ee7b7; }
.red { color: #fda4af; }
.dot { width: 12rpx; height: 12rpx; border-radius: 50%; }
.green-dot { background: #6ee7b7; }
.red-dot { background: #fda4af; }
.yiji-content { font-size: 22rpx; opacity: 0.9; line-height: 1.4; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }

.card { background: #fff; border-radius: 24rpx; padding: 24rpx; margin-bottom: 24rpx; border: 1px solid #f1f5f9; box-shadow: 0 2rpx 4rpx rgba(0,0,0,0.02); width: 100%; box-sizing: border-box; }
.card-header { display: flex; gap: 12rpx; font-weight: bold; color: #334155; margin-bottom: 16rpx; font-size: 28rpx; align-items: center; }
.icon { font-size: 32rpx; }

.dir-grid { display: flex; gap: 12rpx; }
.dir-item { flex: 1; background: #f8fafc; padding: 16rpx; border-radius: 12rpx; text-align: center; border: 1px solid #f1f5f9; }
.dir-label { font-size: 20rpx; color: #94a3b8; display: block; margin-bottom: 4rpx; }
.dir-val { font-weight: bold; color: #334155; font-size: 28rpx; }

.hours-scroll { width: 100%; white-space: nowrap; }
.hours-flex { display: flex; gap: 16rpx; padding-bottom: 8rpx; }
.hour-item { 
    display: inline-flex; flex-direction: column; align-items: center; 
    width: 120rpx; background: #f8fafc; padding: 12rpx; 
    border-radius: 12rpx; border: 1px solid #f1f5f9; 
    flex-shrink: 0;
}
.lucky-hour { background: #ecfdf5; border-color: #d1fae5; }
.hour-zhi { font-weight: bold; color: #334155; font-size: 24rpx; margin-bottom: 4rpx; }
.hour-time { font-size: 20rpx; color: #94a3b8; margin-bottom: 8rpx; transform: scale(0.9); }
.hour-tag { font-size: 20rpx; padding: 2rpx 8rpx; border-radius: 6rpx; font-weight: bold; }
.tag-green { background: #d1fae5; color: #047857; }
.tag-red { background: #ffe4e6; color: #be123c; }

.gods-grid { display: flex; gap: 24rpx; }
.gods-col { flex: 1; }
.gods-head { font-size: 24rpx; font-weight: bold; margin-bottom: 12rpx; }
.green-txt { color: #059669; }
.red-txt { color: #e11d48; }
.gods-tags { display: flex; flex-wrap: wrap; gap: 8rpx; }
.god-tag { font-size: 20rpx; padding: 4rpx 10rpx; border-radius: 6rpx; }
.green-bg { background: #ecfdf5; color: #047857; border: 1px solid #d1fae5; }
.red-bg { background: #ffe4e6; color: #be123c; border: 1px solid #ffe4e6; }

.grid-2 { display: flex; gap: 16rpx; }
.grid-2 .card { flex: 1; margin-bottom: 0; }
.card-header-sm { font-size: 24rpx; font-weight: bold; color: #334155; margin-bottom: 12rpx; }
.row-between { display: flex; justify-content: space-between; font-size: 24rpx; margin-bottom: 8rpx; }
.gray { color: #94a3b8; }
.bold { font-weight: bold; color: #1e293b; }
.divider { height: 1px; background: #f1f5f9; margin: 8rpx 0; }
.peng-item { font-size: 22rpx; background: #f8fafc; padding: 8rpx; border-radius: 8rpx; color: #475569; margin-bottom: 4rpx; }
.indigo { color: #4f46e5; font-weight: bold; margin-right: 4rpx; }
.gray-desc { font-size: 22rpx; color: #94a3b8; margin-top: 8rpx; }

/* DaYun View */
.dayun-scroll { width: 100%; white-space: nowrap; margin-bottom: 24rpx; }
.dayun-flex { display: flex; gap: 16rpx; padding: 8rpx; }
.dayun-item {
    display: inline-flex; flex-direction: column; align-items: center; justify-content: space-between;
    width: 140rpx; height: 200rpx; background: #fff; border: 1px solid #f1f5f9;
    border-radius: 16rpx; padding: 16rpx; transition: all 0.2s;
    flex-shrink: 0;
}
.dayun-item.active { background: #7c3aed; border-color: #7c3aed; box-shadow: 0 4rpx 12rpx rgba(124, 58, 237, 0.3); transform: translateY(-4rpx); }
.dy-age { font-size: 20rpx; color: #94a3b8; }
.dayun-item.active .dy-age { color: #ddd6fe; }
.dy-ganzhi { display: flex; flex-direction: column; align-items: center; }
.dy-god { font-size: 18rpx; color: #64748b; margin-bottom: 4rpx; }
.dayun-item.active .dy-god { color: #ddd6fe; }
.dy-char { font-size: 36rpx; font-weight: 900; color: #1e293b; line-height: 1.1; font-family: serif; }
.dayun-item.active .dy-char { color: #fff; }
.dy-year { font-size: 20rpx; color: #94a3b8; }
.dayun-item.active .dy-year { color: #ddd6fe; }

.detail-card { margin-top: 0; }
.detail-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 24rpx; padding-bottom: 16rpx; border-bottom: 1px solid #f1f5f9; }
.dh-title { font-weight: bold; color: #1e293b; font-size: 32rpx; margin-right: 8rpx; }
.dh-sub { font-size: 24rpx; color: #64748b; }
.dh-range { font-size: 24rpx; font-family: monospace; background: #f1f5f9; padding: 4rpx 12rpx; border-radius: 8rpx; color: #64748b; }

.liunian-grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 12rpx; margin-bottom: 24rpx; }
.ln-item { 
    background: #fff; border: 1px solid #f1f5f9; border-radius: 12rpx; padding: 12rpx 8rpx; 
    text-align: center; cursor: pointer;
}
.ln-item.active { border-color: #8b5cf6; background: #f5f3ff; }
.ln-top { display: flex; justify-content: space-between; margin-bottom: 8rpx; }
.mono { font-family: monospace; font-size: 18rpx; color: #94a3b8; }
.age-badge { font-size: 18rpx; background: #f1f5f9; padding: 0 4rpx; border-radius: 4rpx; color: #64748b; }
.ln-item.active .age-badge { background: #ddd6fe; color: #5b21b6; }
.ln-mid { display: flex; flex-direction: column; align-items: center; }
.ln-god { font-size: 18rpx; color: #94a3b8; margin-bottom: 2rpx; transform: scale(0.9); }
.ln-item.active .ln-god { color: #7c3aed; font-weight: bold; }
.ln-gz { font-size: 28rpx; font-weight: 900; color: #1e293b; font-family: serif; }
.ln-item.active .ln-gz { color: #4c1d95; }

.info-year-box { background: #f8fafc; padding: 16rpx; border-radius: 12rpx; border: 1px solid #e2e8f0; position: relative; overflow: hidden; }
.iy-header { display: flex; align-items: center; gap: 12rpx; margin-bottom: 12rpx; }
.iy-gz { font-size: 36rpx; font-weight: 900; font-family: serif; color: #1e293b; }
.iy-year { font-size: 24rpx; color: #64748b; font-family: monospace; }
.iy-god-tag { background: #f5f3ff; color: #7c3aed; font-size: 20rpx; padding: 2rpx 8rpx; border-radius: 6rpx; font-weight: bold; }
.iy-desc { font-size: 24rpx; color: #475569; line-height: 1.5; }

/* AI Guide */
.ai-card { border: 1px dashed #ddd6fe; background: #f8fafc; }
.ai-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12rpx; }
.ai-head-left { display: flex; align-items: center; gap: 8rpx; color: #4c1d95; font-weight: bold; }
.ai-title { font-size: 28rpx; }
.btn-mini {
    background: #7c3aed; color: #fff; border-radius: 999rpx; padding: 8rpx 20rpx;
    font-size: 24rpx; line-height: 1; border: none;
}
.btn-mini[disabled] { opacity: 0.6; }
.ai-loading { display: flex; align-items: center; gap: 12rpx; color: #64748b; }
.spinner-sm {
    width: 28rpx; height: 28rpx; border-radius: 50%;
    border: 4rpx solid #ddd6fe; border-top-color: #7c3aed; animation: spin 1s linear infinite;
}
.ai-content { display: flex; flex-direction: column; gap: 8rpx; color: #334155; }
.ai-item { display: flex; gap: 12rpx; align-items: flex-start; }
.ai-label {
    min-width: 120rpx;
    background: #ede9fe;
    color: #5b21b6;
    font-size: 22rpx;
    font-weight: bold;
    padding: 4rpx 10rpx;
    border-radius: 8rpx;
    text-align: center;
    flex-shrink: 0;
}
.ai-text { flex: 1; font-size: 24rpx; line-height: 1.6; color: #334155; }
.ai-empty { display: flex; flex-direction: column; gap: 16rpx; color: #94a3b8; }
.btn-secondary {
    background: #fff; border: 1px solid #e2e8f0; border-radius: 12rpx;
    color: #4c1d95; padding: 12rpx 16rpx; font-size: 26rpx;
}

</style>
